# This file is autogenerated by `applaudgen` from `app_store_connect_api.json`.
# Do not modify this file -- YOUR CHANGES WILL BE ERASED!

from .schemas.enums import StringEnum

class AccessibilityDeclarationField(StringEnum):
    SUPPORTS_LARGER_TEXT = 'supportsLargerText'
    SUPPORTS_REDUCED_MOTION = 'supportsReducedMotion'
    SUPPORTS_AUDIO_DESCRIPTIONS = 'supportsAudioDescriptions'
    SUPPORTS_VOICEOVER = 'supportsVoiceover'
    SUPPORTS_CAPTIONS = 'supportsCaptions'
    SUPPORTS_SUFFICIENT_CONTRAST = 'supportsSufficientContrast'
    STATE = 'state'
    SUPPORTS_VOICE_CONTROL = 'supportsVoiceControl'
    SUPPORTS_DARK_INTERFACE = 'supportsDarkInterface'
    SUPPORTS_DIFFERENTIATE_WITHOUT_COLOR_ALONE = 'supportsDifferentiateWithoutColorAlone'
    DEVICE_FAMILY = 'deviceFamily'

class ActorField(StringEnum):
    ACTOR_TYPE = 'actorType'
    API_KEY_ID = 'apiKeyId'
    USER_FIRST_NAME = 'userFirstName'
    USER_LAST_NAME = 'userLastName'
    USER_EMAIL = 'userEmail'

class AlternativeDistributionDomainField(StringEnum):
    CREATED_DATE = 'createdDate'
    REFERENCE_NAME = 'referenceName'
    DOMAIN = 'domain'

class AlternativeDistributionKeyField(StringEnum):
    PUBLIC_KEY = 'publicKey'

class AlternativeDistributionPackageDeltaField(StringEnum):
    URL = 'url'
    FILE_CHECKSUM = 'fileChecksum'
    URL_EXPIRATION_DATE = 'urlExpirationDate'
    ALTERNATIVE_DISTRIBUTION_KEY_BLOB = 'alternativeDistributionKeyBlob'

class AlternativeDistributionPackageVariantField(StringEnum):
    URL = 'url'
    FILE_CHECKSUM = 'fileChecksum'
    URL_EXPIRATION_DATE = 'urlExpirationDate'
    ALTERNATIVE_DISTRIBUTION_KEY_BLOB = 'alternativeDistributionKeyBlob'

class AlternativeDistributionPackageVersionField(StringEnum):
    VERSION = 'version'
    VARIANTS = 'variants'
    URL = 'url'
    STATE = 'state'
    ALTERNATIVE_DISTRIBUTION_PACKAGE = 'alternativeDistributionPackage'
    DELTAS = 'deltas'
    URL_EXPIRATION_DATE = 'urlExpirationDate'
    FILE_CHECKSUM = 'fileChecksum'

class AlternativeDistributionPackageField(StringEnum):
    VERSIONS = 'versions'

class AnalyticsReportInstanceField(StringEnum):
    SEGMENTS = 'segments'
    PROCESSING_DATE = 'processingDate'
    GRANULARITY = 'granularity'

class AnalyticsReportRequestField(StringEnum):
    STOPPED_DUE_TO_INACTIVITY = 'stoppedDueToInactivity'
    REPORTS = 'reports'
    ACCESS_TYPE = 'accessType'

class AnalyticsReportField(StringEnum):
    INSTANCES = 'instances'
    NAME = 'name'
    CATEGORY = 'category'

class AnalyticsReportSegmentField(StringEnum):
    CHECKSUM = 'checksum'
    URL = 'url'
    SIZE_IN_BYTES = 'sizeInBytes'

class AppAvailabilityField(StringEnum):
    AVAILABLE_IN_NEW_TERRITORIES = 'availableInNewTerritories'
    TERRITORY_AVAILABILITIES = 'territoryAvailabilities'

class TerritoryAvailabilityField(StringEnum):
    PRE_ORDER_PUBLISH_DATE = 'preOrderPublishDate'
    AVAILABLE = 'available'
    CONTENT_STATUSES = 'contentStatuses'
    TERRITORY = 'territory'
    RELEASE_DATE = 'releaseDate'
    PRE_ORDER_ENABLED = 'preOrderEnabled'

class AppCategoryField(StringEnum):
    PLATFORMS = 'platforms'
    SUBCATEGORIES = 'subcategories'
    PARENT = 'parent'

class AppClipAdvancedExperienceImageField(StringEnum):
    ASSET_DELIVERY_STATE = 'assetDeliveryState'
    FILE_NAME = 'fileName'
    FILE_SIZE = 'fileSize'
    IMAGE_ASSET = 'imageAsset'
    UPLOAD_OPERATIONS = 'uploadOperations'
    SOURCE_FILE_CHECKSUM = 'sourceFileChecksum'

class AppClipAdvancedExperienceField(StringEnum):
    PLACE_STATUS = 'placeStatus'
    BUSINESS_CATEGORY = 'businessCategory'
    VERSION = 'version'
    HEADER_IMAGE = 'headerImage'
    LOCALIZATIONS = 'localizations'
    ACTION = 'action'
    IS_POWERED_BY = 'isPoweredBy'
    APP_CLIP = 'appClip'
    PLACE = 'place'
    STATUS = 'status'
    LINK = 'link'
    DEFAULT_LANGUAGE = 'defaultLanguage'

class AppClipAppStoreReviewDetailField(StringEnum):
    INVOCATION_URLS = 'invocationUrls'
    APP_CLIP_DEFAULT_EXPERIENCE = 'appClipDefaultExperience'

class AppClipDefaultExperienceLocalizationField(StringEnum):
    LOCALE = 'locale'
    APP_CLIP_HEADER_IMAGE = 'appClipHeaderImage'
    SUBTITLE = 'subtitle'
    APP_CLIP_DEFAULT_EXPERIENCE = 'appClipDefaultExperience'

class AppClipHeaderImageField(StringEnum):
    ASSET_DELIVERY_STATE = 'assetDeliveryState'
    FILE_NAME = 'fileName'
    FILE_SIZE = 'fileSize'
    APP_CLIP_DEFAULT_EXPERIENCE_LOCALIZATION = 'appClipDefaultExperienceLocalization'
    IMAGE_ASSET = 'imageAsset'
    UPLOAD_OPERATIONS = 'uploadOperations'
    SOURCE_FILE_CHECKSUM = 'sourceFileChecksum'

class AppClipDefaultExperienceField(StringEnum):
    APP_CLIP_DEFAULT_EXPERIENCE_LOCALIZATIONS = 'appClipDefaultExperienceLocalizations'
    ACTION = 'action'
    APP_CLIP = 'appClip'
    RELEASE_WITH_APP_STORE_VERSION = 'releaseWithAppStoreVersion'
    APP_CLIP_APP_STORE_REVIEW_DETAIL = 'appClipAppStoreReviewDetail'

class AppStoreVersionField(StringEnum):
    APP_STORE_VERSION_EXPERIMENTS_V2 = 'appStoreVersionExperimentsV2'
    RELEASE_TYPE = 'releaseType'
    BUILD = 'build'
    APP_VERSION_STATE = 'appVersionState'
    ROUTING_APP_COVERAGE = 'routingAppCoverage'
    EARLIEST_RELEASE_DATE = 'earliestReleaseDate'
    VERSION_STRING = 'versionString'
    COPYRIGHT = 'copyright'
    CREATED_DATE = 'createdDate'
    APP_STORE_REVIEW_DETAIL = 'appStoreReviewDetail'
    GAME_CENTER_APP_VERSION = 'gameCenterAppVersion'
    REVIEW_TYPE = 'reviewType'
    DOWNLOADABLE = 'downloadable'
    APP_STORE_VERSION_LOCALIZATIONS = 'appStoreVersionLocalizations'
    CUSTOMER_REVIEWS = 'customerReviews'
    AGE_RATING_DECLARATION = 'ageRatingDeclaration'
    APP_CLIP_DEFAULT_EXPERIENCE = 'appClipDefaultExperience'
    APP = 'app'
    APP_STORE_VERSION_PHASED_RELEASE = 'appStoreVersionPhasedRelease'
    PLATFORM = 'platform'
    APP_STORE_VERSION_EXPERIMENTS = 'appStoreVersionExperiments'
    USES_IDFA = 'usesIdfa'
    ALTERNATIVE_DISTRIBUTION_PACKAGE = 'alternativeDistributionPackage'
    APP_STORE_STATE = 'appStoreState'
    APP_STORE_VERSION_SUBMISSION = 'appStoreVersionSubmission'

class AppClipField(StringEnum):
    BUNDLE_ID = 'bundleId'
    APP_CLIP_ADVANCED_EXPERIENCES = 'appClipAdvancedExperiences'
    APP = 'app'
    APP_CLIP_DEFAULT_EXPERIENCES = 'appClipDefaultExperiences'

class AppCustomProductPageLocalizationField(StringEnum):
    APP_PREVIEW_SETS = 'appPreviewSets'
    LOCALE = 'locale'
    APP_SCREENSHOT_SETS = 'appScreenshotSets'
    APP_CUSTOM_PRODUCT_PAGE_VERSION = 'appCustomProductPageVersion'
    PROMOTIONAL_TEXT = 'promotionalText'

class AppScreenshotSetField(StringEnum):
    SCREENSHOT_DISPLAY_TYPE = 'screenshotDisplayType'
    APP_CUSTOM_PRODUCT_PAGE_LOCALIZATION = 'appCustomProductPageLocalization'
    APP_SCREENSHOTS = 'appScreenshots'
    APP_STORE_VERSION_EXPERIMENT_TREATMENT_LOCALIZATION = 'appStoreVersionExperimentTreatmentLocalization'
    APP_STORE_VERSION_LOCALIZATION = 'appStoreVersionLocalization'

class AppPreviewSetField(StringEnum):
    APP_CUSTOM_PRODUCT_PAGE_LOCALIZATION = 'appCustomProductPageLocalization'
    APP_PREVIEWS = 'appPreviews'
    APP_STORE_VERSION_EXPERIMENT_TREATMENT_LOCALIZATION = 'appStoreVersionExperimentTreatmentLocalization'
    APP_STORE_VERSION_LOCALIZATION = 'appStoreVersionLocalization'
    PREVIEW_TYPE = 'previewType'

class AppCustomProductPageVersionField(StringEnum):
    VERSION = 'version'
    APP_CUSTOM_PRODUCT_PAGE_LOCALIZATIONS = 'appCustomProductPageLocalizations'
    STATE = 'state'
    DEEP_LINK = 'deepLink'
    APP_CUSTOM_PRODUCT_PAGE = 'appCustomProductPage'

class AppCustomProductPageField(StringEnum):
    APP = 'app'
    VISIBLE = 'visible'
    URL = 'url'
    APP_CUSTOM_PRODUCT_PAGE_VERSIONS = 'appCustomProductPageVersions'
    NAME = 'name'

class AppEncryptionDeclarationDocumentField(StringEnum):
    ASSET_DELIVERY_STATE = 'assetDeliveryState'
    FILE_NAME = 'fileName'
    FILE_SIZE = 'fileSize'
    ASSET_TOKEN = 'assetToken'
    DOWNLOAD_URL = 'downloadUrl'
    UPLOAD_OPERATIONS = 'uploadOperations'
    SOURCE_FILE_CHECKSUM = 'sourceFileChecksum'

class AppEncryptionDeclarationField(StringEnum):
    AVAILABLE_ON_FRENCH_STORE = 'availableOnFrenchStore'
    APP = 'app'
    CREATED_DATE = 'createdDate'
    APP_ENCRYPTION_DECLARATION_STATE = 'appEncryptionDeclarationState'
    EXEMPT = 'exempt'
    DOCUMENT_TYPE = 'documentType'
    CONTAINS_PROPRIETARY_CRYPTOGRAPHY = 'containsProprietaryCryptography'
    USES_ENCRYPTION = 'usesEncryption'
    CODE_VALUE = 'codeValue'
    PLATFORM = 'platform'
    DOCUMENT_NAME = 'documentName'
    APP_DESCRIPTION = 'appDescription'
    APP_ENCRYPTION_DECLARATION_DOCUMENT = 'appEncryptionDeclarationDocument'
    DOCUMENT_URL = 'documentUrl'
    UPLOADED_DATE = 'uploadedDate'
    CONTAINS_THIRD_PARTY_CRYPTOGRAPHY = 'containsThirdPartyCryptography'
    BUILDS = 'builds'

class AppField(StringEnum):
    BETA_APP_REVIEW_DETAIL = 'betaAppReviewDetail'
    APP_STORE_VERSION_EXPERIMENTS_V2 = 'appStoreVersionExperimentsV2'
    SKU = 'sku'
    ACCESSIBILITY_DECLARATIONS = 'accessibilityDeclarations'
    BETA_FEEDBACK_CRASH_SUBMISSIONS = 'betaFeedbackCrashSubmissions'
    BETA_APP_LOCALIZATIONS = 'betaAppLocalizations'
    APP_PRICE_SCHEDULE = 'appPriceSchedule'
    PRE_RELEASE_VERSIONS = 'preReleaseVersions'
    PRIMARY_LOCALE = 'primaryLocale'
    SUBSCRIPTION_STATUS_URL_VERSION = 'subscriptionStatusUrlVersion'
    GAME_CENTER_DETAIL = 'gameCenterDetail'
    CUSTOMER_REVIEW_SUMMARIZATIONS = 'customerReviewSummarizations'
    GAME_CENTER_ENABLED_VERSIONS = 'gameCenterEnabledVersions'
    ALTERNATIVE_DISTRIBUTION_KEY = 'alternativeDistributionKey'
    IN_APP_PURCHASES_V2 = 'inAppPurchasesV2'
    SUBSCRIPTION_GRACE_PERIOD = 'subscriptionGracePeriod'
    APP_PRICE_POINTS = 'appPricePoints'
    SUBSCRIPTION_STATUS_URL_VERSION_FOR_SANDBOX = 'subscriptionStatusUrlVersionForSandbox'
    BETA_LICENSE_AGREEMENT = 'betaLicenseAgreement'
    ANALYTICS_REPORT_REQUESTS = 'analyticsReportRequests'
    BETA_GROUPS = 'betaGroups'
    NAME = 'name'
    CUSTOMER_REVIEWS = 'customerReviews'
    BUNDLE_ID = 'bundleId'
    BETA_TESTERS = 'betaTesters'
    ACCESSIBILITY_URL = 'accessibilityUrl'
    APP_CUSTOM_PRODUCT_PAGES = 'appCustomProductPages'
    CONTENT_RIGHTS_DECLARATION = 'contentRightsDeclaration'
    STREAMLINED_PURCHASING_ENABLED = 'streamlinedPurchasingEnabled'
    PERF_POWER_METRICS = 'perfPowerMetrics'
    PROMOTED_PURCHASES = 'promotedPurchases'
    APP_CLIPS = 'appClips'
    APP_ENCRYPTION_DECLARATIONS = 'appEncryptionDeclarations'
    APP_AVAILABILITY_V2 = 'appAvailabilityV2'
    IS_OR_EVER_WAS_MADE_FOR_KIDS = 'isOrEverWasMadeForKids'
    SUBSCRIPTION_STATUS_URL = 'subscriptionStatusUrl'
    CI_PRODUCT = 'ciProduct'
    WEBHOOKS = 'webhooks'
    BETA_FEEDBACK_SCREENSHOT_SUBMISSIONS = 'betaFeedbackScreenshotSubmissions'
    SUBSCRIPTION_GROUPS = 'subscriptionGroups'
    APP_INFOS = 'appInfos'
    SUBSCRIPTION_STATUS_URL_FOR_SANDBOX = 'subscriptionStatusUrlForSandbox'
    IN_APP_PURCHASES = 'inAppPurchases'
    BACKGROUND_ASSETS = 'backgroundAssets'
    APP_EVENTS = 'appEvents'
    END_USER_LICENSE_AGREEMENT = 'endUserLicenseAgreement'
    APP_STORE_VERSIONS = 'appStoreVersions'
    MARKETPLACE_SEARCH_DETAIL = 'marketplaceSearchDetail'
    REVIEW_SUBMISSIONS = 'reviewSubmissions'
    BUILDS = 'builds'

class AppEventLocalizationField(StringEnum):
    APP_EVENT = 'appEvent'
    APP_EVENT_SCREENSHOTS = 'appEventScreenshots'
    LONG_DESCRIPTION = 'longDescription'
    LOCALE = 'locale'
    NAME = 'name'
    SHORT_DESCRIPTION = 'shortDescription'
    APP_EVENT_VIDEO_CLIPS = 'appEventVideoClips'

class AppEventScreenshotField(StringEnum):
    ASSET_DELIVERY_STATE = 'assetDeliveryState'
    FILE_NAME = 'fileName'
    FILE_SIZE = 'fileSize'
    APP_EVENT_LOCALIZATION = 'appEventLocalization'
    ASSET_TOKEN = 'assetToken'
    IMAGE_ASSET = 'imageAsset'
    UPLOAD_OPERATIONS = 'uploadOperations'
    APP_EVENT_ASSET_TYPE = 'appEventAssetType'

class AppEventVideoClipField(StringEnum):
    ASSET_DELIVERY_STATE = 'assetDeliveryState'
    FILE_NAME = 'fileName'
    VIDEO_DELIVERY_STATE = 'videoDeliveryState'
    PREVIEW_FRAME_TIME_CODE = 'previewFrameTimeCode'
    FILE_SIZE = 'fileSize'
    PREVIEW_IMAGE = 'previewImage'
    APP_EVENT_LOCALIZATION = 'appEventLocalization'
    VIDEO_URL = 'videoUrl'
    PREVIEW_FRAME_IMAGE = 'previewFrameImage'
    UPLOAD_OPERATIONS = 'uploadOperations'
    APP_EVENT_ASSET_TYPE = 'appEventAssetType'

class AppEventField(StringEnum):
    BADGE = 'badge'
    PRIORITY = 'priority'
    REFERENCE_NAME = 'referenceName'
    LOCALIZATIONS = 'localizations'
    TERRITORY_SCHEDULES = 'territorySchedules'
    DEEP_LINK = 'deepLink'
    EVENT_STATE = 'eventState'
    PURCHASE_REQUIREMENT = 'purchaseRequirement'
    PRIMARY_LOCALE = 'primaryLocale'
    ARCHIVED_TERRITORY_SCHEDULES = 'archivedTerritorySchedules'
    PURPOSE = 'purpose'

class AppInfoLocalizationField(StringEnum):
    APP_INFO = 'appInfo'
    PRIVACY_CHOICES_URL = 'privacyChoicesUrl'
    SUBTITLE = 'subtitle'
    PRIVACY_POLICY_URL = 'privacyPolicyUrl'
    LOCALE = 'locale'
    PRIVACY_POLICY_TEXT = 'privacyPolicyText'
    NAME = 'name'

class AppInfoField(StringEnum):
    FRANCE_AGE_RATING = 'franceAgeRating'
    APP = 'app'
    PRIMARY_CATEGORY = 'primaryCategory'
    BRAZIL_AGE_RATING = 'brazilAgeRating'
    AUSTRALIA_AGE_RATING = 'australiaAgeRating'
    SECONDARY_CATEGORY = 'secondaryCategory'
    STATE = 'state'
    KOREA_AGE_RATING = 'koreaAgeRating'
    KIDS_AGE_BAND = 'kidsAgeBand'
    PRIMARY_SUBCATEGORY_ONE = 'primarySubcategoryOne'
    SECONDARY_SUBCATEGORY_ONE = 'secondarySubcategoryOne'
    APP_STORE_STATE = 'appStoreState'
    APP_STORE_AGE_RATING = 'appStoreAgeRating'
    APP_INFO_LOCALIZATIONS = 'appInfoLocalizations'
    PRIMARY_SUBCATEGORY_TWO = 'primarySubcategoryTwo'
    AGE_RATING_DECLARATION = 'ageRatingDeclaration'
    SECONDARY_SUBCATEGORY_TWO = 'secondarySubcategoryTwo'
    BRAZIL_AGE_RATING_V2 = 'brazilAgeRatingV2'

class AgeRatingDeclarationField(StringEnum):
    VIOLENCE_REALISTIC = 'violenceRealistic'
    LOOT_BOX = 'lootBox'
    VIOLENCE_REALISTIC_PROLONGED_GRAPHIC_OR_SADISTIC = 'violenceRealisticProlongedGraphicOrSadistic'
    MEDICAL_OR_TREATMENT_INFORMATION = 'medicalOrTreatmentInformation'
    PROFANITY_OR_CRUDE_HUMOR = 'profanityOrCrudeHumor'
    KIDS_AGE_BAND = 'kidsAgeBand'
    CONTESTS = 'contests'
    ALCOHOL_TOBACCO_OR_DRUG_USE_OR_REFERENCES = 'alcoholTobaccoOrDrugUseOrReferences'
    KOREA_AGE_RATING_OVERRIDE = 'koreaAgeRatingOverride'
    UNRESTRICTED_WEB_ACCESS = 'unrestrictedWebAccess'
    GAMBLING_SIMULATED = 'gamblingSimulated'
    MATURE_OR_SUGGESTIVE_THEMES = 'matureOrSuggestiveThemes'
    HORROR_OR_FEAR_THEMES = 'horrorOrFearThemes'
    SEXUAL_CONTENT_OR_NUDITY = 'sexualContentOrNudity'
    VIOLENCE_CARTOON_OR_FANTASY = 'violenceCartoonOrFantasy'
    SEXUAL_CONTENT_GRAPHIC_AND_NUDITY = 'sexualContentGraphicAndNudity'
    GAMBLING = 'gambling'

class AppPreviewField(StringEnum):
    ASSET_DELIVERY_STATE = 'assetDeliveryState'
    FILE_NAME = 'fileName'
    MIME_TYPE = 'mimeType'
    VIDEO_DELIVERY_STATE = 'videoDeliveryState'
    PREVIEW_FRAME_TIME_CODE = 'previewFrameTimeCode'
    FILE_SIZE = 'fileSize'
    PREVIEW_IMAGE = 'previewImage'
    APP_PREVIEW_SET = 'appPreviewSet'
    VIDEO_URL = 'videoUrl'
    PREVIEW_FRAME_IMAGE = 'previewFrameImage'
    UPLOAD_OPERATIONS = 'uploadOperations'
    SOURCE_FILE_CHECKSUM = 'sourceFileChecksum'

class AppPricePointField(StringEnum):
    APP = 'app'
    CUSTOMER_PRICE = 'customerPrice'
    EQUALIZATIONS = 'equalizations'
    PROCEEDS = 'proceeds'
    TERRITORY = 'territory'

class AppPriceScheduleField(StringEnum):
    AUTOMATIC_PRICES = 'automaticPrices'
    APP = 'app'
    BASE_TERRITORY = 'baseTerritory'
    MANUAL_PRICES = 'manualPrices'

class TerritoryField(StringEnum):
    CURRENCY = 'currency'

class AppPriceField(StringEnum):
    START_DATE = 'startDate'
    MANUAL = 'manual'
    APP_PRICE_POINT = 'appPricePoint'
    TERRITORY = 'territory'
    END_DATE = 'endDate'

class AppScreenshotField(StringEnum):
    ASSET_DELIVERY_STATE = 'assetDeliveryState'
    FILE_NAME = 'fileName'
    ASSET_TYPE = 'assetType'
    FILE_SIZE = 'fileSize'
    ASSET_TOKEN = 'assetToken'
    APP_SCREENSHOT_SET = 'appScreenshotSet'
    IMAGE_ASSET = 'imageAsset'
    UPLOAD_OPERATIONS = 'uploadOperations'
    SOURCE_FILE_CHECKSUM = 'sourceFileChecksum'

class AppStoreReviewAttachmentField(StringEnum):
    ASSET_DELIVERY_STATE = 'assetDeliveryState'
    FILE_NAME = 'fileName'
    FILE_SIZE = 'fileSize'
    APP_STORE_REVIEW_DETAIL = 'appStoreReviewDetail'
    UPLOAD_OPERATIONS = 'uploadOperations'
    SOURCE_FILE_CHECKSUM = 'sourceFileChecksum'

class AppStoreReviewDetailField(StringEnum):
    APP_STORE_VERSION = 'appStoreVersion'
    CONTACT_LAST_NAME = 'contactLastName'
    DEMO_ACCOUNT_PASSWORD = 'demoAccountPassword'
    CONTACT_FIRST_NAME = 'contactFirstName'
    CONTACT_EMAIL = 'contactEmail'
    DEMO_ACCOUNT_REQUIRED = 'demoAccountRequired'
    DEMO_ACCOUNT_NAME = 'demoAccountName'
    NOTES = 'notes'
    CONTACT_PHONE = 'contactPhone'
    APP_STORE_REVIEW_ATTACHMENTS = 'appStoreReviewAttachments'

class AppStoreVersionExperimentTreatmentLocalizationField(StringEnum):
    LOCALE = 'locale'
    APP_STORE_VERSION_EXPERIMENT_TREATMENT = 'appStoreVersionExperimentTreatment'
    APP_SCREENSHOT_SETS = 'appScreenshotSets'
    APP_PREVIEW_SETS = 'appPreviewSets'

class AppStoreVersionExperimentTreatmentField(StringEnum):
    PROMOTED_DATE = 'promotedDate'
    APP_STORE_VERSION_EXPERIMENT_TREATMENT_LOCALIZATIONS = 'appStoreVersionExperimentTreatmentLocalizations'
    APP_ICON = 'appIcon'
    APP_STORE_VERSION_EXPERIMENT_V2 = 'appStoreVersionExperimentV2'
    APP_ICON_NAME = 'appIconName'
    APP_STORE_VERSION_EXPERIMENT = 'appStoreVersionExperiment'
    NAME = 'name'

class AppStoreVersionExperimentField(StringEnum):
    APP = 'app'
    LATEST_CONTROL_VERSION = 'latestControlVersion'
    CONTROL_VERSIONS = 'controlVersions'
    START_DATE = 'startDate'
    APP_STORE_VERSION = 'appStoreVersion'
    APP_STORE_VERSION_EXPERIMENT_TREATMENTS = 'appStoreVersionExperimentTreatments'
    TRAFFIC_PROPORTION = 'trafficProportion'
    STATE = 'state'
    NAME = 'name'
    REVIEW_REQUIRED = 'reviewRequired'
    PLATFORM = 'platform'
    END_DATE = 'endDate'

class AppStoreVersionLocalizationField(StringEnum):
    MARKETING_URL = 'marketingUrl'
    APP_STORE_VERSION = 'appStoreVersion'
    SUPPORT_URL = 'supportUrl'
    APP_PREVIEW_SETS = 'appPreviewSets'
    LOCALE = 'locale'
    DESCRIPTION = 'description'
    APP_SCREENSHOT_SETS = 'appScreenshotSets'
    PROMOTIONAL_TEXT = 'promotionalText'
    KEYWORDS = 'keywords'
    WHATS_NEW = 'whatsNew'

class BuildField(StringEnum):
    BUILD_BETA_DETAIL = 'buildBetaDetail'
    VERSION = 'version'
    PROCESSING_STATE = 'processingState'
    MIN_OS_VERSION = 'minOsVersion'
    INDIVIDUAL_TESTERS = 'individualTesters'
    ICONS = 'icons'
    APP_STORE_VERSION = 'appStoreVersion'
    PRE_RELEASE_VERSION = 'preReleaseVersion'
    BETA_GROUPS = 'betaGroups'
    APP = 'app'
    USES_NON_EXEMPT_ENCRYPTION = 'usesNonExemptEncryption'
    PERF_POWER_METRICS = 'perfPowerMetrics'
    BUILD_AUDIENCE_TYPE = 'buildAudienceType'
    EXPIRATION_DATE = 'expirationDate'
    BUILD_BUNDLES = 'buildBundles'
    UPLOADED_DATE = 'uploadedDate'
    APP_ENCRYPTION_DECLARATION = 'appEncryptionDeclaration'
    BETA_APP_REVIEW_SUBMISSION = 'betaAppReviewSubmission'
    LS_MINIMUM_SYSTEM_VERSION = 'lsMinimumSystemVersion'
    DIAGNOSTIC_SIGNATURES = 'diagnosticSignatures'
    COMPUTED_MIN_VISION_OS_VERSION = 'computedMinVisionOsVersion'
    EXPIRED = 'expired'
    COMPUTED_MIN_MAC_OS_VERSION = 'computedMinMacOsVersion'
    BETA_BUILD_LOCALIZATIONS = 'betaBuildLocalizations'
    ICON_ASSET_TOKEN = 'iconAssetToken'

class AppStoreVersionPhasedReleaseField(StringEnum):
    CURRENT_DAY_NUMBER = 'currentDayNumber'
    START_DATE = 'startDate'
    TOTAL_PAUSE_DURATION = 'totalPauseDuration'
    PHASED_RELEASE_STATE = 'phasedReleaseState'

class GameCenterAppVersionField(StringEnum):
    ENABLED = 'enabled'
    COMPATIBILITY_VERSIONS = 'compatibilityVersions'
    APP_STORE_VERSION = 'appStoreVersion'

class RoutingAppCoverageField(StringEnum):
    ASSET_DELIVERY_STATE = 'assetDeliveryState'
    FILE_NAME = 'fileName'
    APP_STORE_VERSION = 'appStoreVersion'
    FILE_SIZE = 'fileSize'
    UPLOAD_OPERATIONS = 'uploadOperations'
    SOURCE_FILE_CHECKSUM = 'sourceFileChecksum'

class AppStoreVersionSubmissionField(StringEnum):
    APP_STORE_VERSION = 'appStoreVersion'

class CiProductField(StringEnum):
    APP = 'app'
    CREATED_DATE = 'createdDate'
    WORKFLOWS = 'workflows'
    ADDITIONAL_REPOSITORIES = 'additionalRepositories'
    NAME = 'name'
    BUILD_RUNS = 'buildRuns'
    BUNDLE_ID = 'bundleId'
    PRODUCT_TYPE = 'productType'
    PRIMARY_REPOSITORIES = 'primaryRepositories'

class BetaGroupField(StringEnum):
    APP = 'app'
    PUBLIC_LINK_LIMIT_ENABLED = 'publicLinkLimitEnabled'
    PUBLIC_LINK_LIMIT = 'publicLinkLimit'
    BETA_RECRUITMENT_CRITERIA = 'betaRecruitmentCriteria'
    CREATED_DATE = 'createdDate'
    HAS_ACCESS_TO_ALL_BUILDS = 'hasAccessToAllBuilds'
    IS_INTERNAL_GROUP = 'isInternalGroup'
    FEEDBACK_ENABLED = 'feedbackEnabled'
    PUBLIC_LINK_ENABLED = 'publicLinkEnabled'
    PUBLIC_LINK_ID = 'publicLinkId'
    PUBLIC_LINK = 'publicLink'
    NAME = 'name'
    IOS_BUILDS_AVAILABLE_FOR_APPLE_VISION = 'iosBuildsAvailableForAppleVision'
    BETA_TESTERS = 'betaTesters'
    IOS_BUILDS_AVAILABLE_FOR_APPLE_SILICON_MAC = 'iosBuildsAvailableForAppleSiliconMac'
    BETA_RECRUITMENT_CRITERION_COMPATIBLE_BUILD_CHECK = 'betaRecruitmentCriterionCompatibleBuildCheck'
    BUILDS = 'builds'

class PreReleaseVersionField(StringEnum):
    APP = 'app'
    PLATFORM = 'platform'
    VERSION = 'version'
    BUILDS = 'builds'

class BetaAppLocalizationField(StringEnum):
    MARKETING_URL = 'marketingUrl'
    APP = 'app'
    PRIVACY_POLICY_URL = 'privacyPolicyUrl'
    FEEDBACK_EMAIL = 'feedbackEmail'
    TV_OS_PRIVACY_POLICY = 'tvOsPrivacyPolicy'
    LOCALE = 'locale'
    DESCRIPTION = 'description'

class BetaLicenseAgreementField(StringEnum):
    APP = 'app'
    AGREEMENT_TEXT = 'agreementText'

class BetaAppReviewDetailField(StringEnum):
    APP = 'app'
    CONTACT_LAST_NAME = 'contactLastName'
    DEMO_ACCOUNT_PASSWORD = 'demoAccountPassword'
    CONTACT_FIRST_NAME = 'contactFirstName'
    CONTACT_EMAIL = 'contactEmail'
    DEMO_ACCOUNT_REQUIRED = 'demoAccountRequired'
    DEMO_ACCOUNT_NAME = 'demoAccountName'
    NOTES = 'notes'
    CONTACT_PHONE = 'contactPhone'

class EndUserLicenseAgreementField(StringEnum):
    APP = 'app'
    AGREEMENT_TEXT = 'agreementText'
    TERRITORIES = 'territories'

class InAppPurchaseField(StringEnum):
    IAP_PRICE_SCHEDULE = 'iapPriceSchedule'
    REFERENCE_NAME = 'referenceName'
    IN_APP_PURCHASE_TYPE = 'inAppPurchaseType'
    IN_APP_PURCHASE_AVAILABILITY = 'inAppPurchaseAvailability'
    PRODUCT_ID = 'productId'
    REVIEW_NOTE = 'reviewNote'
    FAMILY_SHARABLE = 'familySharable'
    STATE = 'state'
    APP_STORE_REVIEW_SCREENSHOT = 'appStoreReviewScreenshot'
    APPS = 'apps'
    PROMOTED_PURCHASE = 'promotedPurchase'
    IMAGES = 'images'
    NAME = 'name'
    CONTENT_HOSTING = 'contentHosting'
    PRICE_POINTS = 'pricePoints'
    CONTENT = 'content'
    IN_APP_PURCHASE_LOCALIZATIONS = 'inAppPurchaseLocalizations'

class SubscriptionGroupField(StringEnum):
    SUBSCRIPTIONS = 'subscriptions'
    SUBSCRIPTION_GROUP_LOCALIZATIONS = 'subscriptionGroupLocalizations'
    REFERENCE_NAME = 'referenceName'

class GameCenterEnabledVersionField(StringEnum):
    APP = 'app'
    ICON_ASSET = 'iconAsset'
    COMPATIBLE_VERSIONS = 'compatibleVersions'
    PLATFORM = 'platform'
    VERSION_STRING = 'versionString'

class PromotedPurchaseField(StringEnum):
    ENABLED = 'enabled'
    STATE = 'state'
    VISIBLE_FOR_ALL_USERS = 'visibleForAllUsers'
    IN_APP_PURCHASE_V2 = 'inAppPurchaseV2'
    SUBSCRIPTION = 'subscription'

class ReviewSubmissionField(StringEnum):
    APP = 'app'
    SUBMITTED_DATE = 'submittedDate'
    APP_STORE_VERSION_FOR_REVIEW = 'appStoreVersionForReview'
    LAST_UPDATED_BY_ACTOR = 'lastUpdatedByActor'
    STATE = 'state'
    ITEMS = 'items'
    SUBMITTED_BY_ACTOR = 'submittedByActor'
    PLATFORM = 'platform'

class SubscriptionGracePeriodField(StringEnum):
    SANDBOX_OPT_IN = 'sandboxOptIn'
    RENEWAL_TYPE = 'renewalType'
    DURATION = 'duration'
    OPT_IN = 'optIn'

class GameCenterDetailField(StringEnum):
    GAME_CENTER_LEADERBOARD_SETS = 'gameCenterLeaderboardSets'
    APP = 'app'
    GAME_CENTER_ACHIEVEMENTS = 'gameCenterAchievements'
    GAME_CENTER_ACTIVITIES = 'gameCenterActivities'
    LEADERBOARD_SET_RELEASES = 'leaderboardSetReleases'
    ARCADE_ENABLED = 'arcadeEnabled'
    GAME_CENTER_CHALLENGES = 'gameCenterChallenges'
    GAME_CENTER_GROUP = 'gameCenterGroup'
    ACHIEVEMENT_RELEASES = 'achievementReleases'
    CHALLENGES_MINIMUM_PLATFORM_VERSIONS = 'challengesMinimumPlatformVersions'
    GAME_CENTER_APP_VERSIONS = 'gameCenterAppVersions'
    LEADERBOARD_RELEASES = 'leaderboardReleases'
    DEFAULT_GROUP_LEADERBOARD = 'defaultGroupLeaderboard'
    DEFAULT_LEADERBOARD = 'defaultLeaderboard'
    CHALLENGE_RELEASES = 'challengeReleases'
    ACTIVITY_RELEASES = 'activityReleases'
    GAME_CENTER_LEADERBOARDS = 'gameCenterLeaderboards'
    CHALLENGE_ENABLED = 'challengeEnabled'

class BackgroundAssetUploadFileField(StringEnum):
    ASSET_DELIVERY_STATE = 'assetDeliveryState'
    FILE_NAME = 'fileName'
    ASSET_TYPE = 'assetType'
    FILE_SIZE = 'fileSize'
    ASSET_TOKEN = 'assetToken'
    UPLOAD_OPERATIONS = 'uploadOperations'
    SOURCE_FILE_CHECKSUM = 'sourceFileChecksum'

class BackgroundAssetVersionInternalBetaReleaseField(StringEnum):
    BACKGROUND_ASSET_VERSION = 'backgroundAssetVersion'
    STATE = 'state'

class BackgroundAssetVersionField(StringEnum):
    CREATED_DATE = 'createdDate'
    VERSION = 'version'
    ASSET_FILE = 'assetFile'
    BACKGROUND_ASSET_UPLOAD_FILES = 'backgroundAssetUploadFiles'
    MANIFEST_FILE = 'manifestFile'
    INTERNAL_BETA_RELEASE = 'internalBetaRelease'
    STATE = 'state'
    PLATFORMS = 'platforms'

class BackgroundAssetField(StringEnum):
    INTERNAL_BETA_VERSION = 'internalBetaVersion'
    VERSIONS = 'versions'
    CREATED_DATE = 'createdDate'
    ASSET_PACK_IDENTIFIER = 'assetPackIdentifier'

class BetaAppClipInvocationField(StringEnum):
    URL = 'url'
    BETA_APP_CLIP_INVOCATION_LOCALIZATIONS = 'betaAppClipInvocationLocalizations'

class BetaAppReviewSubmissionField(StringEnum):
    SUBMITTED_DATE = 'submittedDate'
    BUILD = 'build'
    BETA_REVIEW_STATE = 'betaReviewState'

class BetaBuildLocalizationField(StringEnum):
    LOCALE = 'locale'
    BUILD = 'build'
    WHATS_NEW = 'whatsNew'

class BetaCrashLogField(StringEnum):
    LOG_TEXT = 'logText'

class BetaFeedbackCrashSubmissionField(StringEnum):
    EMAIL = 'email'
    DISK_BYTES_AVAILABLE = 'diskBytesAvailable'
    LOCALE = 'locale'
    SCREEN_HEIGHT_IN_POINTS = 'screenHeightInPoints'
    BUILD = 'build'
    CREATED_DATE = 'createdDate'
    COMMENT = 'comment'
    BATTERY_PERCENTAGE = 'batteryPercentage'
    PAIRED_APPLE_WATCH = 'pairedAppleWatch'
    BUILD_BUNDLE_ID = 'buildBundleId'
    APP_PLATFORM = 'appPlatform'
    APP_UPTIME_IN_MILLISECONDS = 'appUptimeInMilliseconds'
    CRASH_LOG = 'crashLog'
    DISK_BYTES_TOTAL = 'diskBytesTotal'
    SCREEN_WIDTH_IN_POINTS = 'screenWidthInPoints'
    DEVICE_PLATFORM = 'devicePlatform'
    TIME_ZONE = 'timeZone'
    OS_VERSION = 'osVersion'
    TESTER = 'tester'
    ARCHITECTURE = 'architecture'
    DEVICE_MODEL = 'deviceModel'
    CONNECTION_TYPE = 'connectionType'
    DEVICE_FAMILY = 'deviceFamily'

class BetaFeedbackScreenshotSubmissionField(StringEnum):
    EMAIL = 'email'
    DISK_BYTES_AVAILABLE = 'diskBytesAvailable'
    LOCALE = 'locale'
    SCREEN_HEIGHT_IN_POINTS = 'screenHeightInPoints'
    BUILD = 'build'
    CREATED_DATE = 'createdDate'
    COMMENT = 'comment'
    BATTERY_PERCENTAGE = 'batteryPercentage'
    PAIRED_APPLE_WATCH = 'pairedAppleWatch'
    BUILD_BUNDLE_ID = 'buildBundleId'
    APP_PLATFORM = 'appPlatform'
    APP_UPTIME_IN_MILLISECONDS = 'appUptimeInMilliseconds'
    DISK_BYTES_TOTAL = 'diskBytesTotal'
    SCREEN_WIDTH_IN_POINTS = 'screenWidthInPoints'
    DEVICE_PLATFORM = 'devicePlatform'
    TIME_ZONE = 'timeZone'
    OS_VERSION = 'osVersion'
    TESTER = 'tester'
    ARCHITECTURE = 'architecture'
    DEVICE_MODEL = 'deviceModel'
    CONNECTION_TYPE = 'connectionType'
    DEVICE_FAMILY = 'deviceFamily'
    SCREENSHOTS = 'screenshots'

class BetaTesterField(StringEnum):
    EMAIL = 'email'
    FIRST_NAME = 'firstName'
    STATE = 'state'
    APPS = 'apps'
    BETA_GROUPS = 'betaGroups'
    LAST_NAME = 'lastName'
    INVITE_TYPE = 'inviteType'
    BUILDS = 'builds'

class BetaRecruitmentCriteriaField(StringEnum):
    DEVICE_FAMILY_OS_VERSION_FILTERS = 'deviceFamilyOsVersionFilters'
    LAST_MODIFIED_DATE = 'lastModifiedDate'

class BetaRecruitmentCriterionOptionField(StringEnum):
    DEVICE_FAMILY_OS_VERSIONS = 'deviceFamilyOsVersions'

class BuildBetaDetailField(StringEnum):
    EXTERNAL_BUILD_STATE = 'externalBuildState'
    AUTO_NOTIFY_ENABLED = 'autoNotifyEnabled'
    BUILD = 'build'
    INTERNAL_BUILD_STATE = 'internalBuildState'

class BuildIconField(StringEnum):
    ICON_TYPE = 'iconType'
    NAME = 'name'
    ICON_ASSET = 'iconAsset'

class BundleIdField(StringEnum):
    APP = 'app'
    SEED_ID = 'seedId'
    IDENTIFIER = 'identifier'
    NAME = 'name'
    PROFILES = 'profiles'
    PLATFORM = 'platform'
    BUNDLE_ID_CAPABILITIES = 'bundleIdCapabilities'

class ProfileField(StringEnum):
    PROFILE_TYPE = 'profileType'
    CREATED_DATE = 'createdDate'
    UUID = 'uuid'
    PROFILE_CONTENT = 'profileContent'
    NAME = 'name'
    PROFILE_STATE = 'profileState'
    EXPIRATION_DATE = 'expirationDate'
    BUNDLE_ID = 'bundleId'
    PLATFORM = 'platform'
    DEVICES = 'devices'
    CERTIFICATES = 'certificates'

class BundleIdCapabilityField(StringEnum):
    CAPABILITY_TYPE = 'capabilityType'
    SETTINGS = 'settings'

class CertificateField(StringEnum):
    SERIAL_NUMBER = 'serialNumber'
    CERTIFICATE_CONTENT = 'certificateContent'
    NAME = 'name'
    EXPIRATION_DATE = 'expirationDate'
    DISPLAY_NAME = 'displayName'
    CERTIFICATE_TYPE = 'certificateType'
    PASS_TYPE_ID = 'passTypeId'
    PLATFORM = 'platform'
    ACTIVATED = 'activated'

class PassTypeIdField(StringEnum):
    IDENTIFIER = 'identifier'
    NAME = 'name'
    CERTIFICATES = 'certificates'

class CiArtifactField(StringEnum):
    FILE_TYPE = 'fileType'
    DOWNLOAD_URL = 'downloadUrl'
    FILE_NAME = 'fileName'
    FILE_SIZE = 'fileSize'

class CiBuildActionField(StringEnum):
    COMPLETION_STATUS = 'completionStatus'
    BUILD_RUN = 'buildRun'
    ACTION_TYPE = 'actionType'
    ARTIFACTS = 'artifacts'
    ISSUES = 'issues'
    STARTED_DATE = 'startedDate'
    EXECUTION_PROGRESS = 'executionProgress'
    NAME = 'name'
    ISSUE_COUNTS = 'issueCounts'
    FINISHED_DATE = 'finishedDate'
    TEST_RESULTS = 'testResults'
    IS_REQUIRED_TO_PASS = 'isRequiredToPass'

class CiBuildRunField(StringEnum):
    COMPLETION_STATUS = 'completionStatus'
    DESTINATION_COMMIT = 'destinationCommit'
    CANCEL_REASON = 'cancelReason'
    EXECUTION_PROGRESS = 'executionProgress'
    FINISHED_DATE = 'finishedDate'
    WORKFLOW = 'workflow'
    CREATED_DATE = 'createdDate'
    SOURCE_COMMIT = 'sourceCommit'
    NUMBER = 'number'
    IS_PULL_REQUEST_BUILD = 'isPullRequestBuild'
    START_REASON = 'startReason'
    DESTINATION_BRANCH = 'destinationBranch'
    STARTED_DATE = 'startedDate'
    ISSUE_COUNTS = 'issueCounts'
    ACTIONS = 'actions'
    PULL_REQUEST = 'pullRequest'
    SOURCE_BRANCH_OR_TAG = 'sourceBranchOrTag'
    PRODUCT = 'product'
    BUILDS = 'builds'

class CiIssueField(StringEnum):
    ISSUE_TYPE = 'issueType'
    FILE_SOURCE = 'fileSource'
    CATEGORY = 'category'
    MESSAGE = 'message'

class CiMacOsVersionField(StringEnum):
    VERSION = 'version'
    NAME = 'name'
    XCODE_VERSIONS = 'xcodeVersions'

class CiXcodeVersionField(StringEnum):
    VERSION = 'version'
    NAME = 'name'
    TEST_DESTINATIONS = 'testDestinations'
    MAC_OS_VERSIONS = 'macOsVersions'

class ScmRepositoryField(StringEnum):
    DEFAULT_BRANCH = 'defaultBranch'
    SCM_PROVIDER = 'scmProvider'
    LAST_ACCESSED_DATE = 'lastAccessedDate'
    OWNER_NAME = 'ownerName'
    PULL_REQUESTS = 'pullRequests'
    REPOSITORY_NAME = 'repositoryName'
    GIT_REFERENCES = 'gitReferences'
    HTTP_CLONE_URL = 'httpCloneUrl'
    SSH_CLONE_URL = 'sshCloneUrl'

class CiTestResultField(StringEnum):
    CLASS_NAME = 'className'
    DESTINATION_TEST_RESULTS = 'destinationTestResults'
    NAME = 'name'
    STATUS = 'status'
    FILE_SOURCE = 'fileSource'
    MESSAGE = 'message'

class CiWorkflowField(StringEnum):
    REPOSITORY = 'repository'
    CONTAINER_FILE_PATH = 'containerFilePath'
    PULL_REQUEST_START_CONDITION = 'pullRequestStartCondition'
    MAC_OS_VERSION = 'macOsVersion'
    NAME = 'name'
    BUILD_RUNS = 'buildRuns'
    CLEAN = 'clean'
    BRANCH_START_CONDITION = 'branchStartCondition'
    MANUAL_BRANCH_START_CONDITION = 'manualBranchStartCondition'
    LAST_MODIFIED_DATE = 'lastModifiedDate'
    IS_ENABLED = 'isEnabled'
    MANUAL_TAG_START_CONDITION = 'manualTagStartCondition'
    TAG_START_CONDITION = 'tagStartCondition'
    ACTIONS = 'actions'
    IS_LOCKED_FOR_EDITING = 'isLockedForEditing'
    XCODE_VERSION = 'xcodeVersion'
    DESCRIPTION = 'description'
    MANUAL_PULL_REQUEST_START_CONDITION = 'manualPullRequestStartCondition'
    PRODUCT = 'product'
    SCHEDULED_START_CONDITION = 'scheduledStartCondition'

class CustomerReviewResponseField(StringEnum):
    RESPONSE_BODY = 'responseBody'
    STATE = 'state'
    LAST_MODIFIED_DATE = 'lastModifiedDate'
    REVIEW = 'review'

class CustomerReviewField(StringEnum):
    RESPONSE = 'response'
    CREATED_DATE = 'createdDate'
    BODY = 'body'
    TITLE = 'title'
    RATING = 'rating'
    REVIEWER_NICKNAME = 'reviewerNickname'
    TERRITORY = 'territory'

class DeviceField(StringEnum):
    ADDED_DATE = 'addedDate'
    UDID = 'udid'
    NAME = 'name'
    MODEL = 'model'
    PLATFORM = 'platform'
    STATUS = 'status'
    DEVICE_CLASS = 'deviceClass'

class GameCenterAchievementImageField(StringEnum):
    ASSET_DELIVERY_STATE = 'assetDeliveryState'
    FILE_NAME = 'fileName'
    FILE_SIZE = 'fileSize'
    GAME_CENTER_ACHIEVEMENT_LOCALIZATION = 'gameCenterAchievementLocalization'
    IMAGE_ASSET = 'imageAsset'
    UPLOAD_OPERATIONS = 'uploadOperations'

class GameCenterAchievementLocalizationField(StringEnum):
    GAME_CENTER_ACHIEVEMENT_IMAGE = 'gameCenterAchievementImage'
    BEFORE_EARNED_DESCRIPTION = 'beforeEarnedDescription'
    LOCALE = 'locale'
    NAME = 'name'
    GAME_CENTER_ACHIEVEMENT = 'gameCenterAchievement'
    AFTER_EARNED_DESCRIPTION = 'afterEarnedDescription'

class GameCenterAchievementField(StringEnum):
    VENDOR_IDENTIFIER = 'vendorIdentifier'
    ACTIVITY = 'activity'
    REFERENCE_NAME = 'referenceName'
    LOCALIZATIONS = 'localizations'
    REPEATABLE = 'repeatable'
    GAME_CENTER_GROUP = 'gameCenterGroup'
    SHOW_BEFORE_EARNED = 'showBeforeEarned'
    ARCHIVED = 'archived'
    RELEASES = 'releases'
    GROUP_ACHIEVEMENT = 'groupAchievement'
    GAME_CENTER_DETAIL = 'gameCenterDetail'
    POINTS = 'points'
    ACTIVITY_PROPERTIES = 'activityProperties'

class GameCenterAchievementReleaseField(StringEnum):
    GAME_CENTER_ACHIEVEMENT = 'gameCenterAchievement'
    LIVE = 'live'
    GAME_CENTER_DETAIL = 'gameCenterDetail'

class GameCenterActivityField(StringEnum):
    VENDOR_IDENTIFIER = 'vendorIdentifier'
    REFERENCE_NAME = 'referenceName'
    SUPPORTS_PARTY_CODE = 'supportsPartyCode'
    LEADERBOARDS = 'leaderboards'
    GAME_CENTER_GROUP = 'gameCenterGroup'
    MINIMUM_PLAYERS_COUNT = 'minimumPlayersCount'
    PLAY_STYLE = 'playStyle'
    ARCHIVED = 'archived'
    VERSIONS = 'versions'
    ACHIEVEMENTS = 'achievements'
    PROPERTIES = 'properties'
    MAXIMUM_PLAYERS_COUNT = 'maximumPlayersCount'
    GAME_CENTER_DETAIL = 'gameCenterDetail'

class GameCenterActivityVersionField(StringEnum):
    DEFAULT_IMAGE = 'defaultImage'
    ACTIVITY = 'activity'
    VERSION = 'version'
    LOCALIZATIONS = 'localizations'
    STATE = 'state'
    RELEASES = 'releases'
    FALLBACK_URL = 'fallbackUrl'

class GameCenterActivityImageField(StringEnum):
    ASSET_DELIVERY_STATE = 'assetDeliveryState'
    FILE_NAME = 'fileName'
    FILE_SIZE = 'fileSize'
    IMAGE_ASSET = 'imageAsset'
    UPLOAD_OPERATIONS = 'uploadOperations'

class GameCenterActivityLocalizationField(StringEnum):
    VERSION = 'version'
    LOCALE = 'locale'
    DESCRIPTION = 'description'
    NAME = 'name'
    IMAGE = 'image'

class GameCenterActivityVersionReleaseField(StringEnum):
    VERSION = 'version'

class GameCenterChallengeImageField(StringEnum):
    ASSET_DELIVERY_STATE = 'assetDeliveryState'
    FILE_NAME = 'fileName'
    FILE_SIZE = 'fileSize'
    IMAGE_ASSET = 'imageAsset'
    UPLOAD_OPERATIONS = 'uploadOperations'

class GameCenterChallengeLocalizationField(StringEnum):
    VERSION = 'version'
    LOCALE = 'locale'
    DESCRIPTION = 'description'
    NAME = 'name'
    IMAGE = 'image'

class GameCenterChallengeVersionReleaseField(StringEnum):
    VERSION = 'version'

class GameCenterChallengeVersionField(StringEnum):
    DEFAULT_IMAGE = 'defaultImage'
    VERSION = 'version'
    LOCALIZATIONS = 'localizations'
    STATE = 'state'
    RELEASES = 'releases'
    CHALLENGE = 'challenge'

class GameCenterChallengeField(StringEnum):
    VENDOR_IDENTIFIER = 'vendorIdentifier'
    REFERENCE_NAME = 'referenceName'
    LEADERBOARD = 'leaderboard'
    REPEATABLE = 'repeatable'
    GAME_CENTER_GROUP = 'gameCenterGroup'
    ARCHIVED = 'archived'
    VERSIONS = 'versions'
    CHALLENGE_TYPE = 'challengeType'
    ALLOWED_DURATIONS = 'allowedDurations'
    GAME_CENTER_DETAIL = 'gameCenterDetail'

class GameCenterGroupField(StringEnum):
    GAME_CENTER_LEADERBOARD_SETS = 'gameCenterLeaderboardSets'
    GAME_CENTER_ACHIEVEMENTS = 'gameCenterAchievements'
    GAME_CENTER_ACTIVITIES = 'gameCenterActivities'
    REFERENCE_NAME = 'referenceName'
    GAME_CENTER_CHALLENGES = 'gameCenterChallenges'
    GAME_CENTER_DETAILS = 'gameCenterDetails'
    GAME_CENTER_LEADERBOARDS = 'gameCenterLeaderboards'

class GameCenterLeaderboardField(StringEnum):
    LOCALIZATIONS = 'localizations'
    GAME_CENTER_GROUP = 'gameCenterGroup'
    GROUP_LEADERBOARD = 'groupLeaderboard'
    SCORE_SORT_TYPE = 'scoreSortType'
    DEFAULT_FORMATTER = 'defaultFormatter'
    RECURRENCE_START_DATE = 'recurrenceStartDate'
    SCORE_RANGE_START = 'scoreRangeStart'
    GAME_CENTER_DETAIL = 'gameCenterDetail'
    RECURRENCE_RULE = 'recurrenceRule'
    RECURRENCE_DURATION = 'recurrenceDuration'
    VENDOR_IDENTIFIER = 'vendorIdentifier'
    REFERENCE_NAME = 'referenceName'
    ARCHIVED = 'archived'
    RELEASES = 'releases'
    CHALLENGE = 'challenge'
    ACTIVITY_PROPERTIES = 'activityProperties'
    GAME_CENTER_LEADERBOARD_SETS = 'gameCenterLeaderboardSets'
    SCORE_RANGE_END = 'scoreRangeEnd'
    ACTIVITY = 'activity'
    VISIBILITY = 'visibility'
    SUBMISSION_TYPE = 'submissionType'

class GameCenterLeaderboardSetField(StringEnum):
    VENDOR_IDENTIFIER = 'vendorIdentifier'
    GROUP_LEADERBOARD_SET = 'groupLeaderboardSet'
    REFERENCE_NAME = 'referenceName'
    LOCALIZATIONS = 'localizations'
    GAME_CENTER_GROUP = 'gameCenterGroup'
    RELEASES = 'releases'
    GAME_CENTER_DETAIL = 'gameCenterDetail'
    GAME_CENTER_LEADERBOARDS = 'gameCenterLeaderboards'

class GameCenterLeaderboardReleaseField(StringEnum):
    LIVE = 'live'
    GAME_CENTER_LEADERBOARD = 'gameCenterLeaderboard'
    GAME_CENTER_DETAIL = 'gameCenterDetail'

class GameCenterLeaderboardSetReleaseField(StringEnum):
    LIVE = 'live'
    GAME_CENTER_LEADERBOARD_SET = 'gameCenterLeaderboardSet'
    GAME_CENTER_DETAIL = 'gameCenterDetail'

class GameCenterLeaderboardImageField(StringEnum):
    ASSET_DELIVERY_STATE = 'assetDeliveryState'
    FILE_NAME = 'fileName'
    FILE_SIZE = 'fileSize'
    GAME_CENTER_LEADERBOARD_LOCALIZATION = 'gameCenterLeaderboardLocalization'
    IMAGE_ASSET = 'imageAsset'
    UPLOAD_OPERATIONS = 'uploadOperations'

class GameCenterLeaderboardLocalizationField(StringEnum):
    FORMATTER_SUFFIX = 'formatterSuffix'
    GAME_CENTER_LEADERBOARD_IMAGE = 'gameCenterLeaderboardImage'
    FORMATTER_SUFFIX_SINGULAR = 'formatterSuffixSingular'
    LOCALE = 'locale'
    NAME = 'name'
    GAME_CENTER_LEADERBOARD = 'gameCenterLeaderboard'
    FORMATTER_OVERRIDE = 'formatterOverride'

class GameCenterLeaderboardSetImageField(StringEnum):
    ASSET_DELIVERY_STATE = 'assetDeliveryState'
    FILE_NAME = 'fileName'
    GAME_CENTER_LEADERBOARD_SET_LOCALIZATION = 'gameCenterLeaderboardSetLocalization'
    FILE_SIZE = 'fileSize'
    IMAGE_ASSET = 'imageAsset'
    UPLOAD_OPERATIONS = 'uploadOperations'

class GameCenterLeaderboardSetLocalizationField(StringEnum):
    LOCALE = 'locale'
    NAME = 'name'
    GAME_CENTER_LEADERBOARD_SET = 'gameCenterLeaderboardSet'
    GAME_CENTER_LEADERBOARD_SET_IMAGE = 'gameCenterLeaderboardSetImage'

class GameCenterLeaderboardSetMemberLocalizationField(StringEnum):
    NAME = 'name'
    LOCALE = 'locale'
    GAME_CENTER_LEADERBOARD_SET = 'gameCenterLeaderboardSet'
    GAME_CENTER_LEADERBOARD = 'gameCenterLeaderboard'

class GameCenterMatchmakingQueueField(StringEnum):
    CLASSIC_MATCHMAKING_BUNDLE_IDS = 'classicMatchmakingBundleIds'
    RULE_SET = 'ruleSet'
    REFERENCE_NAME = 'referenceName'
    EXPERIMENT_RULE_SET = 'experimentRuleSet'

class GameCenterMatchmakingRuleSetField(StringEnum):
    RULES = 'rules'
    REFERENCE_NAME = 'referenceName'
    TEAMS = 'teams'
    MIN_PLAYERS = 'minPlayers'
    MATCHMAKING_QUEUES = 'matchmakingQueues'
    MAX_PLAYERS = 'maxPlayers'
    RULE_LANGUAGE_VERSION = 'ruleLanguageVersion'

class GameCenterMatchmakingTeamField(StringEnum):
    REFERENCE_NAME = 'referenceName'
    MIN_PLAYERS = 'minPlayers'
    MAX_PLAYERS = 'maxPlayers'

class GameCenterMatchmakingRuleField(StringEnum):
    REFERENCE_NAME = 'referenceName'
    WEIGHT = 'weight'
    EXPRESSION = 'expression'
    DESCRIPTION = 'description'
    TYPE = 'type'

class InAppPurchaseAppStoreReviewScreenshotField(StringEnum):
    ASSET_DELIVERY_STATE = 'assetDeliveryState'
    FILE_NAME = 'fileName'
    ASSET_TYPE = 'assetType'
    FILE_SIZE = 'fileSize'
    ASSET_TOKEN = 'assetToken'
    IN_APP_PURCHASE_V2 = 'inAppPurchaseV2'
    IMAGE_ASSET = 'imageAsset'
    UPLOAD_OPERATIONS = 'uploadOperations'
    SOURCE_FILE_CHECKSUM = 'sourceFileChecksum'

class InAppPurchaseAvailabilityField(StringEnum):
    AVAILABLE_IN_NEW_TERRITORIES = 'availableInNewTerritories'
    AVAILABLE_TERRITORIES = 'availableTerritories'

class InAppPurchaseContentField(StringEnum):
    FILE_NAME = 'fileName'
    FILE_SIZE = 'fileSize'
    URL = 'url'
    LAST_MODIFIED_DATE = 'lastModifiedDate'
    IN_APP_PURCHASE_V2 = 'inAppPurchaseV2'

class InAppPurchaseImageField(StringEnum):
    FILE_NAME = 'fileName'
    FILE_SIZE = 'fileSize'
    IN_APP_PURCHASE = 'inAppPurchase'
    STATE = 'state'
    ASSET_TOKEN = 'assetToken'
    IMAGE_ASSET = 'imageAsset'
    UPLOAD_OPERATIONS = 'uploadOperations'
    SOURCE_FILE_CHECKSUM = 'sourceFileChecksum'

class InAppPurchaseLocalizationField(StringEnum):
    STATE = 'state'
    LOCALE = 'locale'
    DESCRIPTION = 'description'
    NAME = 'name'
    IN_APP_PURCHASE_V2 = 'inAppPurchaseV2'

class InAppPurchasePriceScheduleField(StringEnum):
    AUTOMATIC_PRICES = 'automaticPrices'
    BASE_TERRITORY = 'baseTerritory'
    MANUAL_PRICES = 'manualPrices'

class InAppPurchasePriceField(StringEnum):
    START_DATE = 'startDate'
    MANUAL = 'manual'
    TERRITORY = 'territory'
    IN_APP_PURCHASE_PRICE_POINT = 'inAppPurchasePricePoint'
    END_DATE = 'endDate'

class InAppPurchasePricePointField(StringEnum):
    TERRITORY = 'territory'
    CUSTOMER_PRICE = 'customerPrice'
    EQUALIZATIONS = 'equalizations'
    PROCEEDS = 'proceeds'

class MarketplaceWebhookField(StringEnum):
    ENDPOINT_URL = 'endpointUrl'

class MerchantIdField(StringEnum):
    IDENTIFIER = 'identifier'
    NAME = 'name'
    CERTIFICATES = 'certificates'

class NominationField(StringEnum):
    SUBMITTED_DATE = 'submittedDate'
    PUBLISH_END_DATE = 'publishEndDate'
    HAS_IN_APP_EVENTS = 'hasInAppEvents'
    TYPE = 'type'
    SUPPORTED_TERRITORIES = 'supportedTerritories'
    PRE_ORDER_ENABLED = 'preOrderEnabled'
    CREATED_DATE = 'createdDate'
    STATE = 'state'
    RELATED_APPS = 'relatedApps'
    LOCALES = 'locales'
    NAME = 'name'
    NOTES = 'notes'
    PUBLISH_START_DATE = 'publishStartDate'
    DEVICE_FAMILIES = 'deviceFamilies'
    SUPPLEMENTAL_MATERIALS_URIS = 'supplementalMaterialsUris'
    LAST_MODIFIED_DATE = 'lastModifiedDate'
    SUBMITTED_BY_ACTOR = 'submittedByActor'
    LAST_MODIFIED_BY_ACTOR = 'lastModifiedByActor'
    IN_APP_EVENTS = 'inAppEvents'
    DESCRIPTION = 'description'
    CREATED_BY_ACTOR = 'createdByActor'
    LAUNCH_IN_SELECT_MARKETS_FIRST = 'launchInSelectMarketsFirst'

class ReviewSubmissionItemField(StringEnum):
    APP_EVENT = 'appEvent'
    APP_STORE_VERSION = 'appStoreVersion'
    STATE = 'state'
    APP_STORE_VERSION_EXPERIMENT_V2 = 'appStoreVersionExperimentV2'
    APP_STORE_VERSION_EXPERIMENT = 'appStoreVersionExperiment'
    APP_CUSTOM_PRODUCT_PAGE_VERSION = 'appCustomProductPageVersion'

class SandboxTesterField(StringEnum):
    FIRST_NAME = 'firstName'
    LAST_NAME = 'lastName'
    AC_ACCOUNT_NAME = 'acAccountName'
    TERRITORY = 'territory'
    APPLE_PAY_COMPATIBLE = 'applePayCompatible'
    INTERRUPT_PURCHASES = 'interruptPurchases'
    SUBSCRIPTION_RENEWAL_RATE = 'subscriptionRenewalRate'

class ScmGitReferenceField(StringEnum):
    IS_DELETED = 'isDeleted'
    KIND = 'kind'
    NAME = 'name'
    REPOSITORY = 'repository'
    CANONICAL_NAME = 'canonicalName'

class ScmProviderField(StringEnum):
    URL = 'url'
    SCM_PROVIDER_TYPE = 'scmProviderType'
    REPOSITORIES = 'repositories'

class ScmPullRequestField(StringEnum):
    SOURCE_REPOSITORY_NAME = 'sourceRepositoryName'
    WEB_URL = 'webUrl'
    TITLE = 'title'
    NUMBER = 'number'
    IS_CLOSED = 'isClosed'
    DESTINATION_BRANCH_NAME = 'destinationBranchName'
    DESTINATION_REPOSITORY_OWNER = 'destinationRepositoryOwner'
    REPOSITORY = 'repository'
    IS_CROSS_REPOSITORY = 'isCrossRepository'
    DESTINATION_REPOSITORY_NAME = 'destinationRepositoryName'
    SOURCE_REPOSITORY_OWNER = 'sourceRepositoryOwner'
    SOURCE_BRANCH_NAME = 'sourceBranchName'

class SubscriptionAppStoreReviewScreenshotField(StringEnum):
    ASSET_DELIVERY_STATE = 'assetDeliveryState'
    FILE_NAME = 'fileName'
    ASSET_TYPE = 'assetType'
    FILE_SIZE = 'fileSize'
    ASSET_TOKEN = 'assetToken'
    IMAGE_ASSET = 'imageAsset'
    SUBSCRIPTION = 'subscription'
    UPLOAD_OPERATIONS = 'uploadOperations'
    SOURCE_FILE_CHECKSUM = 'sourceFileChecksum'

class SubscriptionAvailabilityField(StringEnum):
    AVAILABLE_IN_NEW_TERRITORIES = 'availableInNewTerritories'
    AVAILABLE_TERRITORIES = 'availableTerritories'

class SubscriptionGroupLocalizationField(StringEnum):
    STATE = 'state'
    CUSTOM_APP_NAME = 'customAppName'
    LOCALE = 'locale'
    NAME = 'name'
    SUBSCRIPTION_GROUP = 'subscriptionGroup'

class SubscriptionField(StringEnum):
    REVIEW_NOTE = 'reviewNote'
    FAMILY_SHARABLE = 'familySharable'
    SUBSCRIPTION_PERIOD = 'subscriptionPeriod'
    PROMOTED_PURCHASE = 'promotedPurchase'
    OFFER_CODES = 'offerCodes'
    PRODUCT_ID = 'productId'
    STATE = 'state'
    NAME = 'name'
    WIN_BACK_OFFERS = 'winBackOffers'
    PROMOTIONAL_OFFERS = 'promotionalOffers'
    SUBSCRIPTION_AVAILABILITY = 'subscriptionAvailability'
    APP_STORE_REVIEW_SCREENSHOT = 'appStoreReviewScreenshot'
    IMAGES = 'images'
    PRICE_POINTS = 'pricePoints'
    PRICES = 'prices'
    GROUP = 'group'
    INTRODUCTORY_OFFERS = 'introductoryOffers'
    SUBSCRIPTION_LOCALIZATIONS = 'subscriptionLocalizations'
    GROUP_LEVEL = 'groupLevel'

class SubscriptionImageField(StringEnum):
    FILE_NAME = 'fileName'
    FILE_SIZE = 'fileSize'
    STATE = 'state'
    ASSET_TOKEN = 'assetToken'
    IMAGE_ASSET = 'imageAsset'
    SUBSCRIPTION = 'subscription'
    UPLOAD_OPERATIONS = 'uploadOperations'
    SOURCE_FILE_CHECKSUM = 'sourceFileChecksum'

class SubscriptionLocalizationField(StringEnum):
    STATE = 'state'
    LOCALE = 'locale'
    DESCRIPTION = 'description'
    NAME = 'name'
    SUBSCRIPTION = 'subscription'

class SubscriptionOfferCodeCustomCodeField(StringEnum):
    CUSTOM_CODE = 'customCode'
    CREATED_DATE = 'createdDate'
    NUMBER_OF_CODES = 'numberOfCodes'
    EXPIRATION_DATE = 'expirationDate'
    OFFER_CODE = 'offerCode'
    ACTIVE = 'active'

class SubscriptionOfferCodeOneTimeUseCodeField(StringEnum):
    CREATED_DATE = 'createdDate'
    VALUES = 'values'
    NUMBER_OF_CODES = 'numberOfCodes'
    EXPIRATION_DATE = 'expirationDate'
    OFFER_CODE = 'offerCode'
    ACTIVE = 'active'

class SubscriptionOfferCodeField(StringEnum):
    NUMBER_OF_PERIODS = 'numberOfPeriods'
    DURATION = 'duration'
    PRICES = 'prices'
    CUSTOMER_ELIGIBILITIES = 'customerEligibilities'
    CUSTOM_CODES = 'customCodes'
    NAME = 'name'
    ONE_TIME_USE_CODES = 'oneTimeUseCodes'
    SUBSCRIPTION = 'subscription'
    ACTIVE = 'active'
    OFFER_ELIGIBILITY = 'offerEligibility'
    OFFER_MODE = 'offerMode'

class SubscriptionOfferCodePriceField(StringEnum):
    TERRITORY = 'territory'
    SUBSCRIPTION_PRICE_POINT = 'subscriptionPricePoint'

class SubscriptionPricePointField(StringEnum):
    CUSTOMER_PRICE = 'customerPrice'
    EQUALIZATIONS = 'equalizations'
    PROCEEDS = 'proceeds'
    TERRITORY = 'territory'
    PROCEEDS_YEAR2 = 'proceedsYear2'

class SubscriptionPromotionalOfferField(StringEnum):
    NUMBER_OF_PERIODS = 'numberOfPeriods'
    DURATION = 'duration'
    NAME = 'name'
    OFFER_CODE = 'offerCode'
    SUBSCRIPTION = 'subscription'
    PRICES = 'prices'
    OFFER_MODE = 'offerMode'

class SubscriptionPromotionalOfferPriceField(StringEnum):
    TERRITORY = 'territory'
    SUBSCRIPTION_PRICE_POINT = 'subscriptionPricePoint'

class SubscriptionIntroductoryOfferField(StringEnum):
    NUMBER_OF_PERIODS = 'numberOfPeriods'
    SUBSCRIPTION_PRICE_POINT = 'subscriptionPricePoint'
    START_DATE = 'startDate'
    DURATION = 'duration'
    TERRITORY = 'territory'
    SUBSCRIPTION = 'subscription'
    OFFER_MODE = 'offerMode'
    END_DATE = 'endDate'

class SubscriptionPriceField(StringEnum):
    PRESERVED = 'preserved'
    SUBSCRIPTION_PRICE_POINT = 'subscriptionPricePoint'
    START_DATE = 'startDate'
    TERRITORY = 'territory'

class WinBackOfferField(StringEnum):
    OFFER_ID = 'offerId'
    PRIORITY = 'priority'
    CUSTOMER_ELIGIBILITY_WAIT_BETWEEN_OFFERS_IN_MONTHS = 'customerEligibilityWaitBetweenOffersInMonths'
    REFERENCE_NAME = 'referenceName'
    START_DATE = 'startDate'
    END_DATE = 'endDate'
    DURATION = 'duration'
    CUSTOMER_ELIGIBILITY_TIME_SINCE_LAST_SUBSCRIBED_IN_MONTHS = 'customerEligibilityTimeSinceLastSubscribedInMonths'
    PRICES = 'prices'
    PROMOTION_INTENT = 'promotionIntent'
    PERIOD_COUNT = 'periodCount'
    CUSTOMER_ELIGIBILITY_PAID_SUBSCRIPTION_DURATION_IN_MONTHS = 'customerEligibilityPaidSubscriptionDurationInMonths'
    OFFER_MODE = 'offerMode'

class UserInvitationField(StringEnum):
    EMAIL = 'email'
    FIRST_NAME = 'firstName'
    ALL_APPS_VISIBLE = 'allAppsVisible'
    VISIBLE_APPS = 'visibleApps'
    ROLES = 'roles'
    LAST_NAME = 'lastName'
    EXPIRATION_DATE = 'expirationDate'
    PROVISIONING_ALLOWED = 'provisioningAllowed'

class UserField(StringEnum):
    USERNAME = 'username'
    FIRST_NAME = 'firstName'
    ALL_APPS_VISIBLE = 'allAppsVisible'
    VISIBLE_APPS = 'visibleApps'
    ROLES = 'roles'
    LAST_NAME = 'lastName'
    PROVISIONING_ALLOWED = 'provisioningAllowed'

class WebhookField(StringEnum):
    ENABLED = 'enabled'
    APP = 'app'
    DELIVERIES = 'deliveries'
    URL = 'url'
    EVENT_TYPES = 'eventTypes'
    NAME = 'name'

class WinBackOfferPriceField(StringEnum):
    TERRITORY = 'territory'
    SUBSCRIPTION_PRICE_POINT = 'subscriptionPricePoint'

class AppClipAdvancedExperienceLocalizationField(StringEnum):
    LANGUAGE = 'language'
    TITLE = 'title'
    SUBTITLE = 'subtitle'

class CustomerReviewSummarizationField(StringEnum):
    CREATED_DATE = 'createdDate'
    LOCALE = 'locale'
    PLATFORM = 'platform'
    TEXT = 'text'
    TERRITORY = 'territory'

class MarketplaceSearchDetailField(StringEnum):
    CATALOG_URL = 'catalogUrl'

class BetaRecruitmentCriterionCompatibleBuildCheckField(StringEnum):
    HAS_COMPATIBLE_BUILD = 'hasCompatibleBuild'

class BuildBundleField(StringEnum):
    IS_IOS_BUILD_MAC_APP_STORE_COMPATIBLE = 'isIosBuildMacAppStoreCompatible'
    BUILD_BUNDLE_FILE_SIZES = 'buildBundleFileSizes'
    APP_CLIP_DOMAIN_CACHE_STATUS = 'appClipDomainCacheStatus'
    BETA_APP_CLIP_INVOCATIONS = 'betaAppClipInvocations'
    SDK_BUILD = 'sdkBuild'
    SUPPORTED_ARCHITECTURES = 'supportedArchitectures'
    LOCALES = 'locales'
    HAS_PRERENDERED_ICON = 'hasPrerenderedIcon'
    BUNDLE_ID = 'bundleId'
    BUNDLE_TYPE = 'bundleType'
    D_SYM_URL = 'dSYMUrl'
    BA_DOWNLOAD_ALLOWANCE = 'baDownloadAllowance'
    BA_MAX_INSTALL_SIZE = 'baMaxInstallSize'
    APP_CLIP_DOMAIN_DEBUG_STATUS = 'appClipDomainDebugStatus'
    FILE_NAME = 'fileName'
    REQUIRED_CAPABILITIES = 'requiredCapabilities'
    INCLUDES_SYMBOLS = 'includesSymbols'
    DEVICE_PROTOCOLS = 'deviceProtocols'
    USES_LOCATION_SERVICES = 'usesLocationServices'
    PLATFORM_BUILD = 'platformBuild'
    ENTITLEMENTS = 'entitlements'
    HAS_ON_DEMAND_RESOURCES = 'hasOnDemandResources'
    HAS_SIRIKIT = 'hasSirikit'

class AppClipDomainStatuseField(StringEnum):
    LAST_UPDATED_DATE = 'lastUpdatedDate'
    DOMAINS = 'domains'

class BetaAppClipInvocationLocalizationField(StringEnum):
    TITLE = 'title'
    LOCALE = 'locale'

class BuildBundleFileSizeField(StringEnum):
    DEVICE_MODEL = 'deviceModel'
    OS_VERSION = 'osVersion'
    DOWNLOAD_BYTES = 'downloadBytes'
    INSTALL_BYTES = 'installBytes'

class DiagnosticSignatureField(StringEnum):
    DIAGNOSTIC_TYPE = 'diagnosticType'
    SIGNATURE = 'signature'
    WEIGHT = 'weight'
    INSIGHT = 'insight'
    LOGS = 'logs'

class WebhookDeliveryField(StringEnum):
    CREATED_DATE = 'createdDate'
    DELIVERY_STATE = 'deliveryState'
    ERROR_MESSAGE = 'errorMessage'
    REDELIVERY = 'redelivery'
    SENT_DATE = 'sentDate'
    REQUEST = 'request'
    RESPONSE = 'response'
    EVENT = 'event'

class WebhookEventField(StringEnum):
    EVENT_TYPE = 'eventType'
    PAYLOAD = 'payload'
    PING = 'ping'
    CREATED_DATE = 'createdDate'

