# This file is autogenerated by `applaudgen` from `app_store_connect_api.json`.
# Do not modify this file -- YOUR CHANGES WILL BE ERASED!

'''

'''

openapi_version = '3.0.1'
server_url = 'https://api.appstoreconnect.apple.com/'

_title = 'App Store Connect API'
_version = '4.1'

