# This file is autogenerated by `applaudgen` from `app_store_connect_api.json`.
# Do not modify this file -- YOUR CHANGES WILL BE ERASED!

from .schemas.enums import StringEnum

class AccessibilityDeclarationField(StringEnum):
    DEVICE_FAMILY = 'deviceFamily'
    STATE = 'state'
    SUPPORTS_AUDIO_DESCRIPTIONS = 'supportsAudioDescriptions'
    SUPPORTS_CAPTIONS = 'supportsCaptions'
    SUPPORTS_DARK_INTERFACE = 'supportsDarkInterface'
    SUPPORTS_DIFFERENTIATE_WITHOUT_COLOR_ALONE = 'supportsDifferentiateWithoutColorAlone'
    SUPPORTS_LARGER_TEXT = 'supportsLargerText'
    SUPPORTS_REDUCED_MOTION = 'supportsReducedMotion'
    SUPPORTS_SUFFICIENT_CONTRAST = 'supportsSufficientContrast'
    SUPPORTS_VOICE_CONTROL = 'supportsVoiceControl'
    SUPPORTS_VOICEOVER = 'supportsVoiceover'

class ActorField(StringEnum):
    ACTOR_TYPE = 'actorType'
    USER_FIRST_NAME = 'userFirstName'
    USER_LAST_NAME = 'userLastName'
    USER_EMAIL = 'userEmail'
    API_KEY_ID = 'apiKeyId'

class AlternativeDistributionDomainField(StringEnum):
    DOMAIN = 'domain'
    REFERENCE_NAME = 'referenceName'
    CREATED_DATE = 'createdDate'

class AlternativeDistributionKeyField(StringEnum):
    PUBLIC_KEY = 'publicKey'

class AlternativeDistributionPackageDeltaField(StringEnum):
    URL = 'url'
    URL_EXPIRATION_DATE = 'urlExpirationDate'
    ALTERNATIVE_DISTRIBUTION_KEY_BLOB = 'alternativeDistributionKeyBlob'
    FILE_CHECKSUM = 'fileChecksum'

class AlternativeDistributionPackageVariantField(StringEnum):
    URL = 'url'
    URL_EXPIRATION_DATE = 'urlExpirationDate'
    ALTERNATIVE_DISTRIBUTION_KEY_BLOB = 'alternativeDistributionKeyBlob'
    FILE_CHECKSUM = 'fileChecksum'

class AlternativeDistributionPackageVersionField(StringEnum):
    URL = 'url'
    URL_EXPIRATION_DATE = 'urlExpirationDate'
    VERSION = 'version'
    FILE_CHECKSUM = 'fileChecksum'
    STATE = 'state'
    VARIANTS = 'variants'
    DELTAS = 'deltas'
    ALTERNATIVE_DISTRIBUTION_PACKAGE = 'alternativeDistributionPackage'

class AlternativeDistributionPackageField(StringEnum):
    VERSIONS = 'versions'

class AnalyticsReportInstanceField(StringEnum):
    GRANULARITY = 'granularity'
    PROCESSING_DATE = 'processingDate'
    SEGMENTS = 'segments'

class AnalyticsReportRequestField(StringEnum):
    ACCESS_TYPE = 'accessType'
    STOPPED_DUE_TO_INACTIVITY = 'stoppedDueToInactivity'
    REPORTS = 'reports'

class AnalyticsReportField(StringEnum):
    NAME = 'name'
    CATEGORY = 'category'
    INSTANCES = 'instances'

class AnalyticsReportSegmentField(StringEnum):
    CHECKSUM = 'checksum'
    SIZE_IN_BYTES = 'sizeInBytes'
    URL = 'url'

class AppAvailabilityField(StringEnum):
    AVAILABLE_IN_NEW_TERRITORIES = 'availableInNewTerritories'
    TERRITORY_AVAILABILITIES = 'territoryAvailabilities'

class TerritoryAvailabilityField(StringEnum):
    AVAILABLE = 'available'
    RELEASE_DATE = 'releaseDate'
    PRE_ORDER_ENABLED = 'preOrderEnabled'
    PRE_ORDER_PUBLISH_DATE = 'preOrderPublishDate'
    CONTENT_STATUSES = 'contentStatuses'
    TERRITORY = 'territory'

class AppCategoryField(StringEnum):
    PLATFORMS = 'platforms'
    SUBCATEGORIES = 'subcategories'
    PARENT = 'parent'

class AppClipAdvancedExperienceImageField(StringEnum):
    FILE_SIZE = 'fileSize'
    FILE_NAME = 'fileName'
    SOURCE_FILE_CHECKSUM = 'sourceFileChecksum'
    IMAGE_ASSET = 'imageAsset'
    UPLOAD_OPERATIONS = 'uploadOperations'
    ASSET_DELIVERY_STATE = 'assetDeliveryState'

class AppClipAdvancedExperienceField(StringEnum):
    LINK = 'link'
    VERSION = 'version'
    STATUS = 'status'
    ACTION = 'action'
    IS_POWERED_BY = 'isPoweredBy'
    PLACE = 'place'
    PLACE_STATUS = 'placeStatus'
    BUSINESS_CATEGORY = 'businessCategory'
    DEFAULT_LANGUAGE = 'defaultLanguage'
    APP_CLIP = 'appClip'
    HEADER_IMAGE = 'headerImage'
    LOCALIZATIONS = 'localizations'

class AppClipAppStoreReviewDetailField(StringEnum):
    INVOCATION_URLS = 'invocationUrls'
    APP_CLIP_DEFAULT_EXPERIENCE = 'appClipDefaultExperience'

class AppClipDefaultExperienceLocalizationField(StringEnum):
    LOCALE = 'locale'
    SUBTITLE = 'subtitle'
    APP_CLIP_DEFAULT_EXPERIENCE = 'appClipDefaultExperience'
    APP_CLIP_HEADER_IMAGE = 'appClipHeaderImage'

class AppClipHeaderImageField(StringEnum):
    FILE_SIZE = 'fileSize'
    FILE_NAME = 'fileName'
    SOURCE_FILE_CHECKSUM = 'sourceFileChecksum'
    IMAGE_ASSET = 'imageAsset'
    UPLOAD_OPERATIONS = 'uploadOperations'
    ASSET_DELIVERY_STATE = 'assetDeliveryState'
    APP_CLIP_DEFAULT_EXPERIENCE_LOCALIZATION = 'appClipDefaultExperienceLocalization'

class AppClipDefaultExperienceField(StringEnum):
    ACTION = 'action'
    APP_CLIP = 'appClip'
    RELEASE_WITH_APP_STORE_VERSION = 'releaseWithAppStoreVersion'
    APP_CLIP_DEFAULT_EXPERIENCE_LOCALIZATIONS = 'appClipDefaultExperienceLocalizations'
    APP_CLIP_APP_STORE_REVIEW_DETAIL = 'appClipAppStoreReviewDetail'

class AppStoreVersionField(StringEnum):
    PLATFORM = 'platform'
    VERSION_STRING = 'versionString'
    APP_STORE_STATE = 'appStoreState'
    APP_VERSION_STATE = 'appVersionState'
    COPYRIGHT = 'copyright'
    REVIEW_TYPE = 'reviewType'
    RELEASE_TYPE = 'releaseType'
    EARLIEST_RELEASE_DATE = 'earliestReleaseDate'
    USES_IDFA = 'usesIdfa'
    DOWNLOADABLE = 'downloadable'
    CREATED_DATE = 'createdDate'
    APP = 'app'
    AGE_RATING_DECLARATION = 'ageRatingDeclaration'
    APP_STORE_VERSION_LOCALIZATIONS = 'appStoreVersionLocalizations'
    BUILD = 'build'
    APP_STORE_VERSION_PHASED_RELEASE = 'appStoreVersionPhasedRelease'
    GAME_CENTER_APP_VERSION = 'gameCenterAppVersion'
    ROUTING_APP_COVERAGE = 'routingAppCoverage'
    APP_STORE_REVIEW_DETAIL = 'appStoreReviewDetail'
    APP_STORE_VERSION_SUBMISSION = 'appStoreVersionSubmission'
    APP_CLIP_DEFAULT_EXPERIENCE = 'appClipDefaultExperience'
    APP_STORE_VERSION_EXPERIMENTS = 'appStoreVersionExperiments'
    APP_STORE_VERSION_EXPERIMENTS_V2 = 'appStoreVersionExperimentsV2'
    CUSTOMER_REVIEWS = 'customerReviews'
    ALTERNATIVE_DISTRIBUTION_PACKAGE = 'alternativeDistributionPackage'

class AppClipField(StringEnum):
    BUNDLE_ID = 'bundleId'
    APP = 'app'
    APP_CLIP_DEFAULT_EXPERIENCES = 'appClipDefaultExperiences'
    APP_CLIP_ADVANCED_EXPERIENCES = 'appClipAdvancedExperiences'

class AppCustomProductPageLocalizationField(StringEnum):
    LOCALE = 'locale'
    PROMOTIONAL_TEXT = 'promotionalText'
    APP_CUSTOM_PRODUCT_PAGE_VERSION = 'appCustomProductPageVersion'
    APP_SCREENSHOT_SETS = 'appScreenshotSets'
    APP_PREVIEW_SETS = 'appPreviewSets'
    SEARCH_KEYWORDS = 'searchKeywords'

class AppScreenshotSetField(StringEnum):
    SCREENSHOT_DISPLAY_TYPE = 'screenshotDisplayType'
    APP_STORE_VERSION_LOCALIZATION = 'appStoreVersionLocalization'
    APP_CUSTOM_PRODUCT_PAGE_LOCALIZATION = 'appCustomProductPageLocalization'
    APP_STORE_VERSION_EXPERIMENT_TREATMENT_LOCALIZATION = 'appStoreVersionExperimentTreatmentLocalization'
    APP_SCREENSHOTS = 'appScreenshots'

class AppPreviewSetField(StringEnum):
    PREVIEW_TYPE = 'previewType'
    APP_STORE_VERSION_LOCALIZATION = 'appStoreVersionLocalization'
    APP_CUSTOM_PRODUCT_PAGE_LOCALIZATION = 'appCustomProductPageLocalization'
    APP_STORE_VERSION_EXPERIMENT_TREATMENT_LOCALIZATION = 'appStoreVersionExperimentTreatmentLocalization'
    APP_PREVIEWS = 'appPreviews'

class AppCustomProductPageVersionField(StringEnum):
    VERSION = 'version'
    STATE = 'state'
    DEEP_LINK = 'deepLink'
    APP_CUSTOM_PRODUCT_PAGE = 'appCustomProductPage'
    APP_CUSTOM_PRODUCT_PAGE_LOCALIZATIONS = 'appCustomProductPageLocalizations'

class AppCustomProductPageField(StringEnum):
    NAME = 'name'
    URL = 'url'
    VISIBLE = 'visible'
    APP = 'app'
    APP_CUSTOM_PRODUCT_PAGE_VERSIONS = 'appCustomProductPageVersions'

class AppEncryptionDeclarationDocumentField(StringEnum):
    FILE_SIZE = 'fileSize'
    FILE_NAME = 'fileName'
    ASSET_TOKEN = 'assetToken'
    DOWNLOAD_URL = 'downloadUrl'
    SOURCE_FILE_CHECKSUM = 'sourceFileChecksum'
    UPLOAD_OPERATIONS = 'uploadOperations'
    ASSET_DELIVERY_STATE = 'assetDeliveryState'

class AppEncryptionDeclarationField(StringEnum):
    APP_DESCRIPTION = 'appDescription'
    CREATED_DATE = 'createdDate'
    USES_ENCRYPTION = 'usesEncryption'
    EXEMPT = 'exempt'
    CONTAINS_PROPRIETARY_CRYPTOGRAPHY = 'containsProprietaryCryptography'
    CONTAINS_THIRD_PARTY_CRYPTOGRAPHY = 'containsThirdPartyCryptography'
    AVAILABLE_ON_FRENCH_STORE = 'availableOnFrenchStore'
    PLATFORM = 'platform'
    UPLOADED_DATE = 'uploadedDate'
    DOCUMENT_URL = 'documentUrl'
    DOCUMENT_NAME = 'documentName'
    DOCUMENT_TYPE = 'documentType'
    APP_ENCRYPTION_DECLARATION_STATE = 'appEncryptionDeclarationState'
    CODE_VALUE = 'codeValue'
    APP = 'app'
    BUILDS = 'builds'
    APP_ENCRYPTION_DECLARATION_DOCUMENT = 'appEncryptionDeclarationDocument'

class AppField(StringEnum):
    ACCESSIBILITY_URL = 'accessibilityUrl'
    NAME = 'name'
    BUNDLE_ID = 'bundleId'
    SKU = 'sku'
    PRIMARY_LOCALE = 'primaryLocale'
    IS_OR_EVER_WAS_MADE_FOR_KIDS = 'isOrEverWasMadeForKids'
    SUBSCRIPTION_STATUS_URL = 'subscriptionStatusUrl'
    SUBSCRIPTION_STATUS_URL_VERSION = 'subscriptionStatusUrlVersion'
    SUBSCRIPTION_STATUS_URL_FOR_SANDBOX = 'subscriptionStatusUrlForSandbox'
    SUBSCRIPTION_STATUS_URL_VERSION_FOR_SANDBOX = 'subscriptionStatusUrlVersionForSandbox'
    CONTENT_RIGHTS_DECLARATION = 'contentRightsDeclaration'
    STREAMLINED_PURCHASING_ENABLED = 'streamlinedPurchasingEnabled'
    ACCESSIBILITY_DECLARATIONS = 'accessibilityDeclarations'
    APP_ENCRYPTION_DECLARATIONS = 'appEncryptionDeclarations'
    CI_PRODUCT = 'ciProduct'
    BETA_TESTERS = 'betaTesters'
    BETA_GROUPS = 'betaGroups'
    APP_STORE_VERSIONS = 'appStoreVersions'
    APP_TAGS = 'appTags'
    PRE_RELEASE_VERSIONS = 'preReleaseVersions'
    BETA_APP_LOCALIZATIONS = 'betaAppLocalizations'
    BUILDS = 'builds'
    BETA_LICENSE_AGREEMENT = 'betaLicenseAgreement'
    BETA_APP_REVIEW_DETAIL = 'betaAppReviewDetail'
    APP_INFOS = 'appInfos'
    APP_CLIPS = 'appClips'
    APP_PRICE_POINTS = 'appPricePoints'
    END_USER_LICENSE_AGREEMENT = 'endUserLicenseAgreement'
    APP_PRICE_SCHEDULE = 'appPriceSchedule'
    APP_AVAILABILITY_V2 = 'appAvailabilityV2'
    IN_APP_PURCHASES = 'inAppPurchases'
    SUBSCRIPTION_GROUPS = 'subscriptionGroups'
    GAME_CENTER_ENABLED_VERSIONS = 'gameCenterEnabledVersions'
    PERF_POWER_METRICS = 'perfPowerMetrics'
    APP_CUSTOM_PRODUCT_PAGES = 'appCustomProductPages'
    IN_APP_PURCHASES_V2 = 'inAppPurchasesV2'
    PROMOTED_PURCHASES = 'promotedPurchases'
    APP_EVENTS = 'appEvents'
    REVIEW_SUBMISSIONS = 'reviewSubmissions'
    SUBSCRIPTION_GRACE_PERIOD = 'subscriptionGracePeriod'
    CUSTOMER_REVIEWS = 'customerReviews'
    CUSTOMER_REVIEW_SUMMARIZATIONS = 'customerReviewSummarizations'
    GAME_CENTER_DETAIL = 'gameCenterDetail'
    APP_STORE_VERSION_EXPERIMENTS_V2 = 'appStoreVersionExperimentsV2'
    ALTERNATIVE_DISTRIBUTION_KEY = 'alternativeDistributionKey'
    ANALYTICS_REPORT_REQUESTS = 'analyticsReportRequests'
    MARKETPLACE_SEARCH_DETAIL = 'marketplaceSearchDetail'
    BUILD_UPLOADS = 'buildUploads'
    BACKGROUND_ASSETS = 'backgroundAssets'
    BETA_FEEDBACK_SCREENSHOT_SUBMISSIONS = 'betaFeedbackScreenshotSubmissions'
    BETA_FEEDBACK_CRASH_SUBMISSIONS = 'betaFeedbackCrashSubmissions'
    SEARCH_KEYWORDS = 'searchKeywords'
    WEBHOOKS = 'webhooks'

class AppEventLocalizationField(StringEnum):
    LOCALE = 'locale'
    NAME = 'name'
    SHORT_DESCRIPTION = 'shortDescription'
    LONG_DESCRIPTION = 'longDescription'
    APP_EVENT = 'appEvent'
    APP_EVENT_SCREENSHOTS = 'appEventScreenshots'
    APP_EVENT_VIDEO_CLIPS = 'appEventVideoClips'

class AppEventScreenshotField(StringEnum):
    FILE_SIZE = 'fileSize'
    FILE_NAME = 'fileName'
    IMAGE_ASSET = 'imageAsset'
    ASSET_TOKEN = 'assetToken'
    UPLOAD_OPERATIONS = 'uploadOperations'
    ASSET_DELIVERY_STATE = 'assetDeliveryState'
    APP_EVENT_ASSET_TYPE = 'appEventAssetType'
    APP_EVENT_LOCALIZATION = 'appEventLocalization'

class AppEventVideoClipField(StringEnum):
    FILE_SIZE = 'fileSize'
    FILE_NAME = 'fileName'
    PREVIEW_FRAME_TIME_CODE = 'previewFrameTimeCode'
    VIDEO_URL = 'videoUrl'
    PREVIEW_FRAME_IMAGE = 'previewFrameImage'
    PREVIEW_IMAGE = 'previewImage'
    UPLOAD_OPERATIONS = 'uploadOperations'
    ASSET_DELIVERY_STATE = 'assetDeliveryState'
    VIDEO_DELIVERY_STATE = 'videoDeliveryState'
    APP_EVENT_ASSET_TYPE = 'appEventAssetType'
    APP_EVENT_LOCALIZATION = 'appEventLocalization'

class AppEventField(StringEnum):
    REFERENCE_NAME = 'referenceName'
    BADGE = 'badge'
    EVENT_STATE = 'eventState'
    DEEP_LINK = 'deepLink'
    PURCHASE_REQUIREMENT = 'purchaseRequirement'
    PRIMARY_LOCALE = 'primaryLocale'
    PRIORITY = 'priority'
    PURPOSE = 'purpose'
    TERRITORY_SCHEDULES = 'territorySchedules'
    ARCHIVED_TERRITORY_SCHEDULES = 'archivedTerritorySchedules'
    LOCALIZATIONS = 'localizations'

class AppInfoLocalizationField(StringEnum):
    LOCALE = 'locale'
    NAME = 'name'
    SUBTITLE = 'subtitle'
    PRIVACY_POLICY_URL = 'privacyPolicyUrl'
    PRIVACY_CHOICES_URL = 'privacyChoicesUrl'
    PRIVACY_POLICY_TEXT = 'privacyPolicyText'
    APP_INFO = 'appInfo'

class AppInfoField(StringEnum):
    APP_STORE_STATE = 'appStoreState'
    STATE = 'state'
    APP_STORE_AGE_RATING = 'appStoreAgeRating'
    AUSTRALIA_AGE_RATING = 'australiaAgeRating'
    BRAZIL_AGE_RATING = 'brazilAgeRating'
    BRAZIL_AGE_RATING_V2 = 'brazilAgeRatingV2'
    FRANCE_AGE_RATING = 'franceAgeRating'
    KOREA_AGE_RATING = 'koreaAgeRating'
    KIDS_AGE_BAND = 'kidsAgeBand'
    APP = 'app'
    AGE_RATING_DECLARATION = 'ageRatingDeclaration'
    APP_INFO_LOCALIZATIONS = 'appInfoLocalizations'
    PRIMARY_CATEGORY = 'primaryCategory'
    PRIMARY_SUBCATEGORY_ONE = 'primarySubcategoryOne'
    PRIMARY_SUBCATEGORY_TWO = 'primarySubcategoryTwo'
    SECONDARY_CATEGORY = 'secondaryCategory'
    SECONDARY_SUBCATEGORY_ONE = 'secondarySubcategoryOne'
    SECONDARY_SUBCATEGORY_TWO = 'secondarySubcategoryTwo'
    TERRITORY_AGE_RATINGS = 'territoryAgeRatings'

class AgeRatingDeclarationField(StringEnum):
    ADVERTISING = 'advertising'
    ALCOHOL_TOBACCO_OR_DRUG_USE_OR_REFERENCES = 'alcoholTobaccoOrDrugUseOrReferences'
    CONTESTS = 'contests'
    GAMBLING = 'gambling'
    GAMBLING_SIMULATED = 'gamblingSimulated'
    GUNS_OR_OTHER_WEAPONS = 'gunsOrOtherWeapons'
    HEALTH_OR_WELLNESS_TOPICS = 'healthOrWellnessTopics'
    KIDS_AGE_BAND = 'kidsAgeBand'
    LOOT_BOX = 'lootBox'
    MEDICAL_OR_TREATMENT_INFORMATION = 'medicalOrTreatmentInformation'
    MESSAGING_AND_CHAT = 'messagingAndChat'
    PARENTAL_CONTROLS = 'parentalControls'
    PROFANITY_OR_CRUDE_HUMOR = 'profanityOrCrudeHumor'
    AGE_ASSURANCE = 'ageAssurance'
    SEXUAL_CONTENT_GRAPHIC_AND_NUDITY = 'sexualContentGraphicAndNudity'
    SEXUAL_CONTENT_OR_NUDITY = 'sexualContentOrNudity'
    HORROR_OR_FEAR_THEMES = 'horrorOrFearThemes'
    MATURE_OR_SUGGESTIVE_THEMES = 'matureOrSuggestiveThemes'
    UNRESTRICTED_WEB_ACCESS = 'unrestrictedWebAccess'
    USER_GENERATED_CONTENT = 'userGeneratedContent'
    VIOLENCE_CARTOON_OR_FANTASY = 'violenceCartoonOrFantasy'
    VIOLENCE_REALISTIC_PROLONGED_GRAPHIC_OR_SADISTIC = 'violenceRealisticProlongedGraphicOrSadistic'
    VIOLENCE_REALISTIC = 'violenceRealistic'
    AGE_RATING_OVERRIDE = 'ageRatingOverride'
    AGE_RATING_OVERRIDE_V2 = 'ageRatingOverrideV2'
    KOREA_AGE_RATING_OVERRIDE = 'koreaAgeRatingOverride'
    DEVELOPER_AGE_RATING_INFO_URL = 'developerAgeRatingInfoUrl'

class AppPreviewField(StringEnum):
    FILE_SIZE = 'fileSize'
    FILE_NAME = 'fileName'
    SOURCE_FILE_CHECKSUM = 'sourceFileChecksum'
    PREVIEW_FRAME_TIME_CODE = 'previewFrameTimeCode'
    MIME_TYPE = 'mimeType'
    VIDEO_URL = 'videoUrl'
    PREVIEW_FRAME_IMAGE = 'previewFrameImage'
    PREVIEW_IMAGE = 'previewImage'
    UPLOAD_OPERATIONS = 'uploadOperations'
    ASSET_DELIVERY_STATE = 'assetDeliveryState'
    VIDEO_DELIVERY_STATE = 'videoDeliveryState'
    APP_PREVIEW_SET = 'appPreviewSet'

class AppPricePointField(StringEnum):
    CUSTOMER_PRICE = 'customerPrice'
    PROCEEDS = 'proceeds'
    APP = 'app'
    EQUALIZATIONS = 'equalizations'
    TERRITORY = 'territory'

class AppPriceScheduleField(StringEnum):
    APP = 'app'
    BASE_TERRITORY = 'baseTerritory'
    MANUAL_PRICES = 'manualPrices'
    AUTOMATIC_PRICES = 'automaticPrices'

class TerritoryField(StringEnum):
    CURRENCY = 'currency'

class AppPriceField(StringEnum):
    MANUAL = 'manual'
    START_DATE = 'startDate'
    END_DATE = 'endDate'
    APP_PRICE_POINT = 'appPricePoint'
    TERRITORY = 'territory'

class AppScreenshotField(StringEnum):
    FILE_SIZE = 'fileSize'
    FILE_NAME = 'fileName'
    SOURCE_FILE_CHECKSUM = 'sourceFileChecksum'
    IMAGE_ASSET = 'imageAsset'
    ASSET_TOKEN = 'assetToken'
    ASSET_TYPE = 'assetType'
    UPLOAD_OPERATIONS = 'uploadOperations'
    ASSET_DELIVERY_STATE = 'assetDeliveryState'
    APP_SCREENSHOT_SET = 'appScreenshotSet'

class AppStoreReviewAttachmentField(StringEnum):
    FILE_SIZE = 'fileSize'
    FILE_NAME = 'fileName'
    SOURCE_FILE_CHECKSUM = 'sourceFileChecksum'
    UPLOAD_OPERATIONS = 'uploadOperations'
    ASSET_DELIVERY_STATE = 'assetDeliveryState'
    APP_STORE_REVIEW_DETAIL = 'appStoreReviewDetail'

class AppStoreReviewDetailField(StringEnum):
    CONTACT_FIRST_NAME = 'contactFirstName'
    CONTACT_LAST_NAME = 'contactLastName'
    CONTACT_PHONE = 'contactPhone'
    CONTACT_EMAIL = 'contactEmail'
    DEMO_ACCOUNT_NAME = 'demoAccountName'
    DEMO_ACCOUNT_PASSWORD = 'demoAccountPassword'
    DEMO_ACCOUNT_REQUIRED = 'demoAccountRequired'
    NOTES = 'notes'
    APP_STORE_VERSION = 'appStoreVersion'
    APP_STORE_REVIEW_ATTACHMENTS = 'appStoreReviewAttachments'

class AppStoreVersionExperimentTreatmentLocalizationField(StringEnum):
    LOCALE = 'locale'
    APP_STORE_VERSION_EXPERIMENT_TREATMENT = 'appStoreVersionExperimentTreatment'
    APP_SCREENSHOT_SETS = 'appScreenshotSets'
    APP_PREVIEW_SETS = 'appPreviewSets'

class AppStoreVersionExperimentTreatmentField(StringEnum):
    NAME = 'name'
    APP_ICON = 'appIcon'
    APP_ICON_NAME = 'appIconName'
    PROMOTED_DATE = 'promotedDate'
    APP_STORE_VERSION_EXPERIMENT = 'appStoreVersionExperiment'
    APP_STORE_VERSION_EXPERIMENT_V2 = 'appStoreVersionExperimentV2'
    APP_STORE_VERSION_EXPERIMENT_TREATMENT_LOCALIZATIONS = 'appStoreVersionExperimentTreatmentLocalizations'

class AppStoreVersionExperimentField(StringEnum):
    NAME = 'name'
    APP_STORE_VERSION_EXPERIMENT_TREATMENTS = 'appStoreVersionExperimentTreatments'
    APP = 'app'
    APP_STORE_VERSION = 'appStoreVersion'
    STATE = 'state'
    CONTROL_VERSIONS = 'controlVersions'
    REVIEW_REQUIRED = 'reviewRequired'
    LATEST_CONTROL_VERSION = 'latestControlVersion'
    PLATFORM = 'platform'
    TRAFFIC_PROPORTION = 'trafficProportion'
    START_DATE = 'startDate'
    END_DATE = 'endDate'

class AppStoreVersionLocalizationField(StringEnum):
    DESCRIPTION = 'description'
    LOCALE = 'locale'
    KEYWORDS = 'keywords'
    MARKETING_URL = 'marketingUrl'
    PROMOTIONAL_TEXT = 'promotionalText'
    SUPPORT_URL = 'supportUrl'
    WHATS_NEW = 'whatsNew'
    APP_STORE_VERSION = 'appStoreVersion'
    APP_SCREENSHOT_SETS = 'appScreenshotSets'
    APP_PREVIEW_SETS = 'appPreviewSets'
    SEARCH_KEYWORDS = 'searchKeywords'

class BuildField(StringEnum):
    VERSION = 'version'
    UPLOADED_DATE = 'uploadedDate'
    EXPIRATION_DATE = 'expirationDate'
    EXPIRED = 'expired'
    MIN_OS_VERSION = 'minOsVersion'
    LS_MINIMUM_SYSTEM_VERSION = 'lsMinimumSystemVersion'
    COMPUTED_MIN_MAC_OS_VERSION = 'computedMinMacOsVersion'
    COMPUTED_MIN_VISION_OS_VERSION = 'computedMinVisionOsVersion'
    ICON_ASSET_TOKEN = 'iconAssetToken'
    PROCESSING_STATE = 'processingState'
    BUILD_AUDIENCE_TYPE = 'buildAudienceType'
    USES_NON_EXEMPT_ENCRYPTION = 'usesNonExemptEncryption'
    PRE_RELEASE_VERSION = 'preReleaseVersion'
    INDIVIDUAL_TESTERS = 'individualTesters'
    BETA_GROUPS = 'betaGroups'
    BETA_BUILD_LOCALIZATIONS = 'betaBuildLocalizations'
    APP_ENCRYPTION_DECLARATION = 'appEncryptionDeclaration'
    BETA_APP_REVIEW_SUBMISSION = 'betaAppReviewSubmission'
    APP = 'app'
    BUILD_BETA_DETAIL = 'buildBetaDetail'
    APP_STORE_VERSION = 'appStoreVersion'
    ICONS = 'icons'
    BUILD_BUNDLES = 'buildBundles'
    BUILD_UPLOAD = 'buildUpload'
    PERF_POWER_METRICS = 'perfPowerMetrics'
    DIAGNOSTIC_SIGNATURES = 'diagnosticSignatures'

class AppStoreVersionPhasedReleaseField(StringEnum):
    PHASED_RELEASE_STATE = 'phasedReleaseState'
    START_DATE = 'startDate'
    TOTAL_PAUSE_DURATION = 'totalPauseDuration'
    CURRENT_DAY_NUMBER = 'currentDayNumber'

class GameCenterAppVersionField(StringEnum):
    ENABLED = 'enabled'
    COMPATIBILITY_VERSIONS = 'compatibilityVersions'
    APP_STORE_VERSION = 'appStoreVersion'

class RoutingAppCoverageField(StringEnum):
    FILE_SIZE = 'fileSize'
    FILE_NAME = 'fileName'
    SOURCE_FILE_CHECKSUM = 'sourceFileChecksum'
    UPLOAD_OPERATIONS = 'uploadOperations'
    ASSET_DELIVERY_STATE = 'assetDeliveryState'
    APP_STORE_VERSION = 'appStoreVersion'

class AppStoreVersionSubmissionField(StringEnum):
    APP_STORE_VERSION = 'appStoreVersion'

class CiProductField(StringEnum):
    NAME = 'name'
    CREATED_DATE = 'createdDate'
    PRODUCT_TYPE = 'productType'
    APP = 'app'
    BUNDLE_ID = 'bundleId'
    WORKFLOWS = 'workflows'
    PRIMARY_REPOSITORIES = 'primaryRepositories'
    ADDITIONAL_REPOSITORIES = 'additionalRepositories'
    BUILD_RUNS = 'buildRuns'

class BetaGroupField(StringEnum):
    NAME = 'name'
    CREATED_DATE = 'createdDate'
    IS_INTERNAL_GROUP = 'isInternalGroup'
    HAS_ACCESS_TO_ALL_BUILDS = 'hasAccessToAllBuilds'
    PUBLIC_LINK_ENABLED = 'publicLinkEnabled'
    PUBLIC_LINK_ID = 'publicLinkId'
    PUBLIC_LINK_LIMIT_ENABLED = 'publicLinkLimitEnabled'
    PUBLIC_LINK_LIMIT = 'publicLinkLimit'
    PUBLIC_LINK = 'publicLink'
    FEEDBACK_ENABLED = 'feedbackEnabled'
    IOS_BUILDS_AVAILABLE_FOR_APPLE_SILICON_MAC = 'iosBuildsAvailableForAppleSiliconMac'
    IOS_BUILDS_AVAILABLE_FOR_APPLE_VISION = 'iosBuildsAvailableForAppleVision'
    APP = 'app'
    BUILDS = 'builds'
    BETA_TESTERS = 'betaTesters'
    BETA_RECRUITMENT_CRITERIA = 'betaRecruitmentCriteria'
    BETA_RECRUITMENT_CRITERION_COMPATIBLE_BUILD_CHECK = 'betaRecruitmentCriterionCompatibleBuildCheck'

class PreReleaseVersionField(StringEnum):
    VERSION = 'version'
    PLATFORM = 'platform'
    BUILDS = 'builds'
    APP = 'app'

class BetaAppLocalizationField(StringEnum):
    FEEDBACK_EMAIL = 'feedbackEmail'
    MARKETING_URL = 'marketingUrl'
    PRIVACY_POLICY_URL = 'privacyPolicyUrl'
    TV_OS_PRIVACY_POLICY = 'tvOsPrivacyPolicy'
    DESCRIPTION = 'description'
    LOCALE = 'locale'
    APP = 'app'

class BetaLicenseAgreementField(StringEnum):
    AGREEMENT_TEXT = 'agreementText'
    APP = 'app'

class BetaAppReviewDetailField(StringEnum):
    CONTACT_FIRST_NAME = 'contactFirstName'
    CONTACT_LAST_NAME = 'contactLastName'
    CONTACT_PHONE = 'contactPhone'
    CONTACT_EMAIL = 'contactEmail'
    DEMO_ACCOUNT_NAME = 'demoAccountName'
    DEMO_ACCOUNT_PASSWORD = 'demoAccountPassword'
    DEMO_ACCOUNT_REQUIRED = 'demoAccountRequired'
    NOTES = 'notes'
    APP = 'app'

class EndUserLicenseAgreementField(StringEnum):
    AGREEMENT_TEXT = 'agreementText'
    APP = 'app'
    TERRITORIES = 'territories'

class InAppPurchaseField(StringEnum):
    NAME = 'name'
    REVIEW_NOTE = 'reviewNote'
    APP_STORE_REVIEW_SCREENSHOT = 'appStoreReviewScreenshot'
    REFERENCE_NAME = 'referenceName'
    PRODUCT_ID = 'productId'
    IN_APP_PURCHASE_AVAILABILITY = 'inAppPurchaseAvailability'
    FAMILY_SHARABLE = 'familySharable'
    IN_APP_PURCHASE_LOCALIZATIONS = 'inAppPurchaseLocalizations'
    CONTENT_HOSTING = 'contentHosting'
    IAP_PRICE_SCHEDULE = 'iapPriceSchedule'
    STATE = 'state'
    PRICE_POINTS = 'pricePoints'
    IN_APP_PURCHASE_TYPE = 'inAppPurchaseType'
    APPS = 'apps'
    CONTENT = 'content'
    PROMOTED_PURCHASE = 'promotedPurchase'
    IMAGES = 'images'

class SubscriptionGroupField(StringEnum):
    REFERENCE_NAME = 'referenceName'
    SUBSCRIPTIONS = 'subscriptions'
    SUBSCRIPTION_GROUP_LOCALIZATIONS = 'subscriptionGroupLocalizations'

class GameCenterEnabledVersionField(StringEnum):
    PLATFORM = 'platform'
    VERSION_STRING = 'versionString'
    ICON_ASSET = 'iconAsset'
    COMPATIBLE_VERSIONS = 'compatibleVersions'
    APP = 'app'

class PromotedPurchaseField(StringEnum):
    VISIBLE_FOR_ALL_USERS = 'visibleForAllUsers'
    ENABLED = 'enabled'
    STATE = 'state'
    IN_APP_PURCHASE_V2 = 'inAppPurchaseV2'
    SUBSCRIPTION = 'subscription'

class ReviewSubmissionField(StringEnum):
    PLATFORM = 'platform'
    SUBMITTED_DATE = 'submittedDate'
    STATE = 'state'
    APP = 'app'
    ITEMS = 'items'
    APP_STORE_VERSION_FOR_REVIEW = 'appStoreVersionForReview'
    SUBMITTED_BY_ACTOR = 'submittedByActor'
    LAST_UPDATED_BY_ACTOR = 'lastUpdatedByActor'

class SubscriptionGracePeriodField(StringEnum):
    OPT_IN = 'optIn'
    SANDBOX_OPT_IN = 'sandboxOptIn'
    DURATION = 'duration'
    RENEWAL_TYPE = 'renewalType'

class GameCenterDetailField(StringEnum):
    ARCADE_ENABLED = 'arcadeEnabled'
    CHALLENGE_ENABLED = 'challengeEnabled'
    APP = 'app'
    GAME_CENTER_APP_VERSIONS = 'gameCenterAppVersions'
    GAME_CENTER_GROUP = 'gameCenterGroup'
    GAME_CENTER_LEADERBOARDS = 'gameCenterLeaderboards'
    GAME_CENTER_LEADERBOARD_SETS = 'gameCenterLeaderboardSets'
    GAME_CENTER_ACHIEVEMENTS = 'gameCenterAchievements'
    GAME_CENTER_ACTIVITIES = 'gameCenterActivities'
    GAME_CENTER_CHALLENGES = 'gameCenterChallenges'
    DEFAULT_LEADERBOARD = 'defaultLeaderboard'
    DEFAULT_GROUP_LEADERBOARD = 'defaultGroupLeaderboard'
    ACHIEVEMENT_RELEASES = 'achievementReleases'
    ACTIVITY_RELEASES = 'activityReleases'
    CHALLENGE_RELEASES = 'challengeReleases'
    LEADERBOARD_RELEASES = 'leaderboardReleases'
    LEADERBOARD_SET_RELEASES = 'leaderboardSetReleases'
    CHALLENGES_MINIMUM_PLATFORM_VERSIONS = 'challengesMinimumPlatformVersions'

class BackgroundAssetUploadFileField(StringEnum):
    ASSET_DELIVERY_STATE = 'assetDeliveryState'
    ASSET_TOKEN = 'assetToken'
    ASSET_TYPE = 'assetType'
    FILE_NAME = 'fileName'
    FILE_SIZE = 'fileSize'
    SOURCE_FILE_CHECKSUM = 'sourceFileChecksum'
    SOURCE_FILE_CHECKSUMS = 'sourceFileChecksums'
    UPLOAD_OPERATIONS = 'uploadOperations'

class BackgroundAssetVersionAppStoreReleaseField(StringEnum):
    STATE = 'state'
    BACKGROUND_ASSET_VERSION = 'backgroundAssetVersion'

class BackgroundAssetVersionExternalBetaReleaseField(StringEnum):
    STATE = 'state'
    BACKGROUND_ASSET_VERSION = 'backgroundAssetVersion'

class BackgroundAssetVersionInternalBetaReleaseField(StringEnum):
    STATE = 'state'
    BACKGROUND_ASSET_VERSION = 'backgroundAssetVersion'

class BackgroundAssetVersionField(StringEnum):
    CREATED_DATE = 'createdDate'
    PLATFORMS = 'platforms'
    STATE = 'state'
    VERSION = 'version'
    BACKGROUND_ASSET = 'backgroundAsset'
    INTERNAL_BETA_RELEASE = 'internalBetaRelease'
    EXTERNAL_BETA_RELEASE = 'externalBetaRelease'
    APP_STORE_RELEASE = 'appStoreRelease'
    ASSET_FILE = 'assetFile'
    MANIFEST_FILE = 'manifestFile'
    BACKGROUND_ASSET_UPLOAD_FILES = 'backgroundAssetUploadFiles'

class BackgroundAssetField(StringEnum):
    ASSET_PACK_IDENTIFIER = 'assetPackIdentifier'
    CREATED_DATE = 'createdDate'
    APP = 'app'
    VERSIONS = 'versions'
    APP_STORE_VERSION = 'appStoreVersion'
    INTERNAL_BETA_VERSION = 'internalBetaVersion'
    EXTERNAL_BETA_VERSION = 'externalBetaVersion'

class BetaAppClipInvocationField(StringEnum):
    URL = 'url'
    BETA_APP_CLIP_INVOCATION_LOCALIZATIONS = 'betaAppClipInvocationLocalizations'

class BetaAppReviewSubmissionField(StringEnum):
    BETA_REVIEW_STATE = 'betaReviewState'
    SUBMITTED_DATE = 'submittedDate'
    BUILD = 'build'

class BetaBuildLocalizationField(StringEnum):
    WHATS_NEW = 'whatsNew'
    LOCALE = 'locale'
    BUILD = 'build'

class BetaCrashLogField(StringEnum):
    LOG_TEXT = 'logText'

class BetaFeedbackCrashSubmissionField(StringEnum):
    CREATED_DATE = 'createdDate'
    COMMENT = 'comment'
    EMAIL = 'email'
    DEVICE_MODEL = 'deviceModel'
    OS_VERSION = 'osVersion'
    LOCALE = 'locale'
    TIME_ZONE = 'timeZone'
    ARCHITECTURE = 'architecture'
    CONNECTION_TYPE = 'connectionType'
    PAIRED_APPLE_WATCH = 'pairedAppleWatch'
    APP_UPTIME_IN_MILLISECONDS = 'appUptimeInMilliseconds'
    DISK_BYTES_AVAILABLE = 'diskBytesAvailable'
    DISK_BYTES_TOTAL = 'diskBytesTotal'
    BATTERY_PERCENTAGE = 'batteryPercentage'
    SCREEN_WIDTH_IN_POINTS = 'screenWidthInPoints'
    SCREEN_HEIGHT_IN_POINTS = 'screenHeightInPoints'
    APP_PLATFORM = 'appPlatform'
    DEVICE_PLATFORM = 'devicePlatform'
    DEVICE_FAMILY = 'deviceFamily'
    BUILD_BUNDLE_ID = 'buildBundleId'
    CRASH_LOG = 'crashLog'
    BUILD = 'build'
    TESTER = 'tester'

class BetaFeedbackScreenshotSubmissionField(StringEnum):
    CREATED_DATE = 'createdDate'
    COMMENT = 'comment'
    EMAIL = 'email'
    DEVICE_MODEL = 'deviceModel'
    OS_VERSION = 'osVersion'
    LOCALE = 'locale'
    TIME_ZONE = 'timeZone'
    ARCHITECTURE = 'architecture'
    CONNECTION_TYPE = 'connectionType'
    PAIRED_APPLE_WATCH = 'pairedAppleWatch'
    APP_UPTIME_IN_MILLISECONDS = 'appUptimeInMilliseconds'
    DISK_BYTES_AVAILABLE = 'diskBytesAvailable'
    DISK_BYTES_TOTAL = 'diskBytesTotal'
    BATTERY_PERCENTAGE = 'batteryPercentage'
    SCREEN_WIDTH_IN_POINTS = 'screenWidthInPoints'
    SCREEN_HEIGHT_IN_POINTS = 'screenHeightInPoints'
    APP_PLATFORM = 'appPlatform'
    DEVICE_PLATFORM = 'devicePlatform'
    DEVICE_FAMILY = 'deviceFamily'
    BUILD_BUNDLE_ID = 'buildBundleId'
    SCREENSHOTS = 'screenshots'
    BUILD = 'build'
    TESTER = 'tester'

class BetaTesterField(StringEnum):
    FIRST_NAME = 'firstName'
    LAST_NAME = 'lastName'
    EMAIL = 'email'
    INVITE_TYPE = 'inviteType'
    STATE = 'state'
    APPS = 'apps'
    BETA_GROUPS = 'betaGroups'
    BUILDS = 'builds'

class BetaRecruitmentCriteriaField(StringEnum):
    LAST_MODIFIED_DATE = 'lastModifiedDate'
    DEVICE_FAMILY_OS_VERSION_FILTERS = 'deviceFamilyOsVersionFilters'

class BetaRecruitmentCriterionOptionField(StringEnum):
    DEVICE_FAMILY_OS_VERSIONS = 'deviceFamilyOsVersions'

class BuildBetaDetailField(StringEnum):
    AUTO_NOTIFY_ENABLED = 'autoNotifyEnabled'
    INTERNAL_BUILD_STATE = 'internalBuildState'
    EXTERNAL_BUILD_STATE = 'externalBuildState'
    BUILD = 'build'

class BuildUploadFileField(StringEnum):
    ASSET_DELIVERY_STATE = 'assetDeliveryState'
    ASSET_TOKEN = 'assetToken'
    ASSET_TYPE = 'assetType'
    FILE_NAME = 'fileName'
    FILE_SIZE = 'fileSize'
    SOURCE_FILE_CHECKSUMS = 'sourceFileChecksums'
    UPLOAD_OPERATIONS = 'uploadOperations'
    UTI = 'uti'

class BuildUploadField(StringEnum):
    CF_BUNDLE_SHORT_VERSION_STRING = 'cfBundleShortVersionString'
    CF_BUNDLE_VERSION = 'cfBundleVersion'
    CREATED_DATE = 'createdDate'
    STATE = 'state'
    PLATFORM = 'platform'
    UPLOADED_DATE = 'uploadedDate'
    BUILD = 'build'
    ASSET_FILE = 'assetFile'
    ASSET_DESCRIPTION_FILE = 'assetDescriptionFile'
    ASSET_SPI_FILE = 'assetSpiFile'
    BUILD_UPLOAD_FILES = 'buildUploadFiles'

class BuildIconField(StringEnum):
    ICON_ASSET = 'iconAsset'
    ICON_TYPE = 'iconType'
    MASKED = 'masked'
    NAME = 'name'

class BundleIdField(StringEnum):
    NAME = 'name'
    PLATFORM = 'platform'
    IDENTIFIER = 'identifier'
    SEED_ID = 'seedId'
    PROFILES = 'profiles'
    BUNDLE_ID_CAPABILITIES = 'bundleIdCapabilities'
    APP = 'app'

class ProfileField(StringEnum):
    NAME = 'name'
    PLATFORM = 'platform'
    PROFILE_TYPE = 'profileType'
    PROFILE_STATE = 'profileState'
    PROFILE_CONTENT = 'profileContent'
    UUID = 'uuid'
    CREATED_DATE = 'createdDate'
    EXPIRATION_DATE = 'expirationDate'
    BUNDLE_ID = 'bundleId'
    DEVICES = 'devices'
    CERTIFICATES = 'certificates'

class BundleIdCapabilityField(StringEnum):
    CAPABILITY_TYPE = 'capabilityType'
    SETTINGS = 'settings'

class CertificateField(StringEnum):
    NAME = 'name'
    CERTIFICATE_TYPE = 'certificateType'
    DISPLAY_NAME = 'displayName'
    SERIAL_NUMBER = 'serialNumber'
    PLATFORM = 'platform'
    EXPIRATION_DATE = 'expirationDate'
    CERTIFICATE_CONTENT = 'certificateContent'
    ACTIVATED = 'activated'
    PASS_TYPE_ID = 'passTypeId'

class PassTypeIdField(StringEnum):
    NAME = 'name'
    IDENTIFIER = 'identifier'
    CERTIFICATES = 'certificates'

class CiArtifactField(StringEnum):
    FILE_TYPE = 'fileType'
    FILE_NAME = 'fileName'
    FILE_SIZE = 'fileSize'
    DOWNLOAD_URL = 'downloadUrl'

class CiBuildActionField(StringEnum):
    NAME = 'name'
    ACTION_TYPE = 'actionType'
    STARTED_DATE = 'startedDate'
    FINISHED_DATE = 'finishedDate'
    ISSUE_COUNTS = 'issueCounts'
    EXECUTION_PROGRESS = 'executionProgress'
    COMPLETION_STATUS = 'completionStatus'
    IS_REQUIRED_TO_PASS = 'isRequiredToPass'
    BUILD_RUN = 'buildRun'
    ARTIFACTS = 'artifacts'
    ISSUES = 'issues'
    TEST_RESULTS = 'testResults'

class CiBuildRunField(StringEnum):
    NUMBER = 'number'
    CREATED_DATE = 'createdDate'
    STARTED_DATE = 'startedDate'
    FINISHED_DATE = 'finishedDate'
    SOURCE_COMMIT = 'sourceCommit'
    DESTINATION_COMMIT = 'destinationCommit'
    IS_PULL_REQUEST_BUILD = 'isPullRequestBuild'
    ISSUE_COUNTS = 'issueCounts'
    EXECUTION_PROGRESS = 'executionProgress'
    COMPLETION_STATUS = 'completionStatus'
    START_REASON = 'startReason'
    CANCEL_REASON = 'cancelReason'
    BUILDS = 'builds'
    WORKFLOW = 'workflow'
    PRODUCT = 'product'
    SOURCE_BRANCH_OR_TAG = 'sourceBranchOrTag'
    DESTINATION_BRANCH = 'destinationBranch'
    ACTIONS = 'actions'
    PULL_REQUEST = 'pullRequest'

class CiIssueField(StringEnum):
    ISSUE_TYPE = 'issueType'
    MESSAGE = 'message'
    FILE_SOURCE = 'fileSource'
    CATEGORY = 'category'

class CiMacOsVersionField(StringEnum):
    VERSION = 'version'
    NAME = 'name'
    XCODE_VERSIONS = 'xcodeVersions'

class CiXcodeVersionField(StringEnum):
    VERSION = 'version'
    NAME = 'name'
    TEST_DESTINATIONS = 'testDestinations'
    MAC_OS_VERSIONS = 'macOsVersions'

class ScmRepositoryField(StringEnum):
    LAST_ACCESSED_DATE = 'lastAccessedDate'
    HTTP_CLONE_URL = 'httpCloneUrl'
    SSH_CLONE_URL = 'sshCloneUrl'
    OWNER_NAME = 'ownerName'
    REPOSITORY_NAME = 'repositoryName'
    SCM_PROVIDER = 'scmProvider'
    DEFAULT_BRANCH = 'defaultBranch'
    GIT_REFERENCES = 'gitReferences'
    PULL_REQUESTS = 'pullRequests'

class CiTestResultField(StringEnum):
    CLASS_NAME = 'className'
    NAME = 'name'
    STATUS = 'status'
    FILE_SOURCE = 'fileSource'
    MESSAGE = 'message'
    DESTINATION_TEST_RESULTS = 'destinationTestResults'

class CiWorkflowField(StringEnum):
    NAME = 'name'
    DESCRIPTION = 'description'
    BRANCH_START_CONDITION = 'branchStartCondition'
    TAG_START_CONDITION = 'tagStartCondition'
    PULL_REQUEST_START_CONDITION = 'pullRequestStartCondition'
    SCHEDULED_START_CONDITION = 'scheduledStartCondition'
    MANUAL_BRANCH_START_CONDITION = 'manualBranchStartCondition'
    MANUAL_TAG_START_CONDITION = 'manualTagStartCondition'
    MANUAL_PULL_REQUEST_START_CONDITION = 'manualPullRequestStartCondition'
    ACTIONS = 'actions'
    IS_ENABLED = 'isEnabled'
    IS_LOCKED_FOR_EDITING = 'isLockedForEditing'
    CLEAN = 'clean'
    CONTAINER_FILE_PATH = 'containerFilePath'
    LAST_MODIFIED_DATE = 'lastModifiedDate'
    PRODUCT = 'product'
    REPOSITORY = 'repository'
    XCODE_VERSION = 'xcodeVersion'
    MAC_OS_VERSION = 'macOsVersion'
    BUILD_RUNS = 'buildRuns'

class CustomerReviewResponseField(StringEnum):
    RESPONSE_BODY = 'responseBody'
    LAST_MODIFIED_DATE = 'lastModifiedDate'
    STATE = 'state'
    REVIEW = 'review'

class CustomerReviewField(StringEnum):
    RATING = 'rating'
    TITLE = 'title'
    BODY = 'body'
    REVIEWER_NICKNAME = 'reviewerNickname'
    CREATED_DATE = 'createdDate'
    TERRITORY = 'territory'
    RESPONSE = 'response'

class DeviceField(StringEnum):
    NAME = 'name'
    PLATFORM = 'platform'
    UDID = 'udid'
    DEVICE_CLASS = 'deviceClass'
    STATUS = 'status'
    MODEL = 'model'
    ADDED_DATE = 'addedDate'

class GameCenterAchievementImageField(StringEnum):
    FILE_SIZE = 'fileSize'
    FILE_NAME = 'fileName'
    IMAGE_ASSET = 'imageAsset'
    UPLOAD_OPERATIONS = 'uploadOperations'
    ASSET_DELIVERY_STATE = 'assetDeliveryState'
    GAME_CENTER_ACHIEVEMENT_LOCALIZATION = 'gameCenterAchievementLocalization'

class GameCenterAchievementLocalizationField(StringEnum):
    LOCALE = 'locale'
    NAME = 'name'
    BEFORE_EARNED_DESCRIPTION = 'beforeEarnedDescription'
    AFTER_EARNED_DESCRIPTION = 'afterEarnedDescription'
    GAME_CENTER_ACHIEVEMENT = 'gameCenterAchievement'
    GAME_CENTER_ACHIEVEMENT_IMAGE = 'gameCenterAchievementImage'

class GameCenterAchievementField(StringEnum):
    REFERENCE_NAME = 'referenceName'
    VENDOR_IDENTIFIER = 'vendorIdentifier'
    POINTS = 'points'
    SHOW_BEFORE_EARNED = 'showBeforeEarned'
    REPEATABLE = 'repeatable'
    ARCHIVED = 'archived'
    ACTIVITY_PROPERTIES = 'activityProperties'
    GAME_CENTER_DETAIL = 'gameCenterDetail'
    GAME_CENTER_GROUP = 'gameCenterGroup'
    GROUP_ACHIEVEMENT = 'groupAchievement'
    LOCALIZATIONS = 'localizations'
    RELEASES = 'releases'
    ACTIVITY = 'activity'

class GameCenterAchievementReleaseField(StringEnum):
    LIVE = 'live'
    GAME_CENTER_DETAIL = 'gameCenterDetail'
    GAME_CENTER_ACHIEVEMENT = 'gameCenterAchievement'

class GameCenterActivityField(StringEnum):
    REFERENCE_NAME = 'referenceName'
    VENDOR_IDENTIFIER = 'vendorIdentifier'
    PLAY_STYLE = 'playStyle'
    MINIMUM_PLAYERS_COUNT = 'minimumPlayersCount'
    MAXIMUM_PLAYERS_COUNT = 'maximumPlayersCount'
    SUPPORTS_PARTY_CODE = 'supportsPartyCode'
    ARCHIVED = 'archived'
    PROPERTIES = 'properties'
    GAME_CENTER_DETAIL = 'gameCenterDetail'
    GAME_CENTER_GROUP = 'gameCenterGroup'
    ACHIEVEMENTS = 'achievements'
    LEADERBOARDS = 'leaderboards'
    VERSIONS = 'versions'

class GameCenterActivityVersionField(StringEnum):
    VERSION = 'version'
    STATE = 'state'
    FALLBACK_URL = 'fallbackUrl'
    ACTIVITY = 'activity'
    LOCALIZATIONS = 'localizations'
    DEFAULT_IMAGE = 'defaultImage'
    RELEASES = 'releases'

class GameCenterActivityImageField(StringEnum):
    FILE_SIZE = 'fileSize'
    FILE_NAME = 'fileName'
    IMAGE_ASSET = 'imageAsset'
    UPLOAD_OPERATIONS = 'uploadOperations'
    ASSET_DELIVERY_STATE = 'assetDeliveryState'

class GameCenterActivityLocalizationField(StringEnum):
    LOCALE = 'locale'
    NAME = 'name'
    DESCRIPTION = 'description'
    VERSION = 'version'
    IMAGE = 'image'

class GameCenterActivityVersionReleaseField(StringEnum):
    VERSION = 'version'

class GameCenterChallengeImageField(StringEnum):
    FILE_SIZE = 'fileSize'
    FILE_NAME = 'fileName'
    IMAGE_ASSET = 'imageAsset'
    UPLOAD_OPERATIONS = 'uploadOperations'
    ASSET_DELIVERY_STATE = 'assetDeliveryState'

class GameCenterChallengeLocalizationField(StringEnum):
    LOCALE = 'locale'
    NAME = 'name'
    DESCRIPTION = 'description'
    VERSION = 'version'
    IMAGE = 'image'

class GameCenterChallengeVersionReleaseField(StringEnum):
    VERSION = 'version'

class GameCenterChallengeVersionField(StringEnum):
    VERSION = 'version'
    STATE = 'state'
    CHALLENGE = 'challenge'
    LOCALIZATIONS = 'localizations'
    RELEASES = 'releases'
    DEFAULT_IMAGE = 'defaultImage'

class GameCenterChallengeField(StringEnum):
    REFERENCE_NAME = 'referenceName'
    VENDOR_IDENTIFIER = 'vendorIdentifier'
    ARCHIVED = 'archived'
    CHALLENGE_TYPE = 'challengeType'
    REPEATABLE = 'repeatable'
    GAME_CENTER_DETAIL = 'gameCenterDetail'
    GAME_CENTER_GROUP = 'gameCenterGroup'
    VERSIONS = 'versions'
    LEADERBOARD = 'leaderboard'

class GameCenterGroupField(StringEnum):
    REFERENCE_NAME = 'referenceName'
    GAME_CENTER_DETAILS = 'gameCenterDetails'
    GAME_CENTER_LEADERBOARDS = 'gameCenterLeaderboards'
    GAME_CENTER_LEADERBOARD_SETS = 'gameCenterLeaderboardSets'
    GAME_CENTER_ACHIEVEMENTS = 'gameCenterAchievements'
    GAME_CENTER_ACTIVITIES = 'gameCenterActivities'
    GAME_CENTER_CHALLENGES = 'gameCenterChallenges'

class GameCenterLeaderboardField(StringEnum):
    DEFAULT_FORMATTER = 'defaultFormatter'
    REFERENCE_NAME = 'referenceName'
    VENDOR_IDENTIFIER = 'vendorIdentifier'
    SUBMISSION_TYPE = 'submissionType'
    SCORE_SORT_TYPE = 'scoreSortType'
    SCORE_RANGE_START = 'scoreRangeStart'
    SCORE_RANGE_END = 'scoreRangeEnd'
    RECURRENCE_START_DATE = 'recurrenceStartDate'
    RECURRENCE_DURATION = 'recurrenceDuration'
    RECURRENCE_RULE = 'recurrenceRule'
    ARCHIVED = 'archived'
    ACTIVITY_PROPERTIES = 'activityProperties'
    VISIBILITY = 'visibility'
    GAME_CENTER_DETAIL = 'gameCenterDetail'
    GAME_CENTER_GROUP = 'gameCenterGroup'
    GROUP_LEADERBOARD = 'groupLeaderboard'
    GAME_CENTER_LEADERBOARD_SETS = 'gameCenterLeaderboardSets'
    LOCALIZATIONS = 'localizations'
    RELEASES = 'releases'
    ACTIVITY = 'activity'
    CHALLENGE = 'challenge'

class GameCenterLeaderboardSetField(StringEnum):
    REFERENCE_NAME = 'referenceName'
    VENDOR_IDENTIFIER = 'vendorIdentifier'
    GAME_CENTER_DETAIL = 'gameCenterDetail'
    GAME_CENTER_GROUP = 'gameCenterGroup'
    GROUP_LEADERBOARD_SET = 'groupLeaderboardSet'
    LOCALIZATIONS = 'localizations'
    GAME_CENTER_LEADERBOARDS = 'gameCenterLeaderboards'
    RELEASES = 'releases'

class GameCenterLeaderboardReleaseField(StringEnum):
    LIVE = 'live'
    GAME_CENTER_DETAIL = 'gameCenterDetail'
    GAME_CENTER_LEADERBOARD = 'gameCenterLeaderboard'

class GameCenterLeaderboardSetReleaseField(StringEnum):
    LIVE = 'live'
    GAME_CENTER_DETAIL = 'gameCenterDetail'
    GAME_CENTER_LEADERBOARD_SET = 'gameCenterLeaderboardSet'

class GameCenterLeaderboardImageField(StringEnum):
    FILE_SIZE = 'fileSize'
    FILE_NAME = 'fileName'
    IMAGE_ASSET = 'imageAsset'
    UPLOAD_OPERATIONS = 'uploadOperations'
    ASSET_DELIVERY_STATE = 'assetDeliveryState'
    GAME_CENTER_LEADERBOARD_LOCALIZATION = 'gameCenterLeaderboardLocalization'

class GameCenterLeaderboardLocalizationField(StringEnum):
    LOCALE = 'locale'
    NAME = 'name'
    FORMATTER_OVERRIDE = 'formatterOverride'
    FORMATTER_SUFFIX = 'formatterSuffix'
    FORMATTER_SUFFIX_SINGULAR = 'formatterSuffixSingular'
    DESCRIPTION = 'description'
    GAME_CENTER_LEADERBOARD = 'gameCenterLeaderboard'
    GAME_CENTER_LEADERBOARD_IMAGE = 'gameCenterLeaderboardImage'

class GameCenterLeaderboardSetImageField(StringEnum):
    FILE_SIZE = 'fileSize'
    FILE_NAME = 'fileName'
    IMAGE_ASSET = 'imageAsset'
    UPLOAD_OPERATIONS = 'uploadOperations'
    ASSET_DELIVERY_STATE = 'assetDeliveryState'
    GAME_CENTER_LEADERBOARD_SET_LOCALIZATION = 'gameCenterLeaderboardSetLocalization'

class GameCenterLeaderboardSetLocalizationField(StringEnum):
    LOCALE = 'locale'
    NAME = 'name'
    GAME_CENTER_LEADERBOARD_SET = 'gameCenterLeaderboardSet'
    GAME_CENTER_LEADERBOARD_SET_IMAGE = 'gameCenterLeaderboardSetImage'

class GameCenterLeaderboardSetMemberLocalizationField(StringEnum):
    NAME = 'name'
    LOCALE = 'locale'
    GAME_CENTER_LEADERBOARD_SET = 'gameCenterLeaderboardSet'
    GAME_CENTER_LEADERBOARD = 'gameCenterLeaderboard'

class GameCenterMatchmakingQueueField(StringEnum):
    REFERENCE_NAME = 'referenceName'
    CLASSIC_MATCHMAKING_BUNDLE_IDS = 'classicMatchmakingBundleIds'
    RULE_SET = 'ruleSet'
    EXPERIMENT_RULE_SET = 'experimentRuleSet'

class GameCenterMatchmakingRuleSetField(StringEnum):
    REFERENCE_NAME = 'referenceName'
    RULE_LANGUAGE_VERSION = 'ruleLanguageVersion'
    MIN_PLAYERS = 'minPlayers'
    MAX_PLAYERS = 'maxPlayers'
    TEAMS = 'teams'
    RULES = 'rules'
    MATCHMAKING_QUEUES = 'matchmakingQueues'

class GameCenterMatchmakingTeamField(StringEnum):
    REFERENCE_NAME = 'referenceName'
    MIN_PLAYERS = 'minPlayers'
    MAX_PLAYERS = 'maxPlayers'

class GameCenterMatchmakingRuleField(StringEnum):
    REFERENCE_NAME = 'referenceName'
    DESCRIPTION = 'description'
    TYPE = 'type'
    EXPRESSION = 'expression'
    WEIGHT = 'weight'

class InAppPurchaseAppStoreReviewScreenshotField(StringEnum):
    FILE_SIZE = 'fileSize'
    FILE_NAME = 'fileName'
    SOURCE_FILE_CHECKSUM = 'sourceFileChecksum'
    IMAGE_ASSET = 'imageAsset'
    ASSET_TOKEN = 'assetToken'
    ASSET_TYPE = 'assetType'
    UPLOAD_OPERATIONS = 'uploadOperations'
    ASSET_DELIVERY_STATE = 'assetDeliveryState'
    IN_APP_PURCHASE_V2 = 'inAppPurchaseV2'

class InAppPurchaseAvailabilityField(StringEnum):
    AVAILABLE_IN_NEW_TERRITORIES = 'availableInNewTerritories'
    AVAILABLE_TERRITORIES = 'availableTerritories'

class InAppPurchaseContentField(StringEnum):
    FILE_NAME = 'fileName'
    FILE_SIZE = 'fileSize'
    URL = 'url'
    LAST_MODIFIED_DATE = 'lastModifiedDate'
    IN_APP_PURCHASE_V2 = 'inAppPurchaseV2'

class InAppPurchaseImageField(StringEnum):
    FILE_SIZE = 'fileSize'
    FILE_NAME = 'fileName'
    SOURCE_FILE_CHECKSUM = 'sourceFileChecksum'
    ASSET_TOKEN = 'assetToken'
    IMAGE_ASSET = 'imageAsset'
    UPLOAD_OPERATIONS = 'uploadOperations'
    STATE = 'state'
    IN_APP_PURCHASE = 'inAppPurchase'

class InAppPurchaseLocalizationField(StringEnum):
    NAME = 'name'
    LOCALE = 'locale'
    DESCRIPTION = 'description'
    STATE = 'state'
    IN_APP_PURCHASE_V2 = 'inAppPurchaseV2'

class InAppPurchasePriceScheduleField(StringEnum):
    BASE_TERRITORY = 'baseTerritory'
    MANUAL_PRICES = 'manualPrices'
    AUTOMATIC_PRICES = 'automaticPrices'

class InAppPurchasePriceField(StringEnum):
    START_DATE = 'startDate'
    END_DATE = 'endDate'
    MANUAL = 'manual'
    IN_APP_PURCHASE_PRICE_POINT = 'inAppPurchasePricePoint'
    TERRITORY = 'territory'

class InAppPurchasePricePointField(StringEnum):
    CUSTOMER_PRICE = 'customerPrice'
    PROCEEDS = 'proceeds'
    TERRITORY = 'territory'
    EQUALIZATIONS = 'equalizations'

class MarketplaceWebhookField(StringEnum):
    ENDPOINT_URL = 'endpointUrl'

class MerchantIdField(StringEnum):
    NAME = 'name'
    IDENTIFIER = 'identifier'
    CERTIFICATES = 'certificates'

class NominationField(StringEnum):
    NAME = 'name'
    TYPE = 'type'
    DESCRIPTION = 'description'
    CREATED_DATE = 'createdDate'
    LAST_MODIFIED_DATE = 'lastModifiedDate'
    SUBMITTED_DATE = 'submittedDate'
    STATE = 'state'
    PUBLISH_START_DATE = 'publishStartDate'
    PUBLISH_END_DATE = 'publishEndDate'
    DEVICE_FAMILIES = 'deviceFamilies'
    LOCALES = 'locales'
    SUPPLEMENTAL_MATERIALS_URIS = 'supplementalMaterialsUris'
    HAS_IN_APP_EVENTS = 'hasInAppEvents'
    LAUNCH_IN_SELECT_MARKETS_FIRST = 'launchInSelectMarketsFirst'
    NOTES = 'notes'
    PRE_ORDER_ENABLED = 'preOrderEnabled'
    RELATED_APPS = 'relatedApps'
    CREATED_BY_ACTOR = 'createdByActor'
    LAST_MODIFIED_BY_ACTOR = 'lastModifiedByActor'
    SUBMITTED_BY_ACTOR = 'submittedByActor'
    IN_APP_EVENTS = 'inAppEvents'
    SUPPORTED_TERRITORIES = 'supportedTerritories'

class ReviewSubmissionItemField(StringEnum):
    STATE = 'state'
    APP_STORE_VERSION = 'appStoreVersion'
    APP_CUSTOM_PRODUCT_PAGE_VERSION = 'appCustomProductPageVersion'
    APP_STORE_VERSION_EXPERIMENT = 'appStoreVersionExperiment'
    APP_STORE_VERSION_EXPERIMENT_V2 = 'appStoreVersionExperimentV2'
    APP_EVENT = 'appEvent'
    BACKGROUND_ASSET_VERSION = 'backgroundAssetVersion'

class SandboxTesterField(StringEnum):
    FIRST_NAME = 'firstName'
    LAST_NAME = 'lastName'
    AC_ACCOUNT_NAME = 'acAccountName'
    TERRITORY = 'territory'
    APPLE_PAY_COMPATIBLE = 'applePayCompatible'
    INTERRUPT_PURCHASES = 'interruptPurchases'
    SUBSCRIPTION_RENEWAL_RATE = 'subscriptionRenewalRate'

class ScmGitReferenceField(StringEnum):
    NAME = 'name'
    CANONICAL_NAME = 'canonicalName'
    IS_DELETED = 'isDeleted'
    KIND = 'kind'
    REPOSITORY = 'repository'

class ScmProviderField(StringEnum):
    SCM_PROVIDER_TYPE = 'scmProviderType'
    URL = 'url'
    REPOSITORIES = 'repositories'

class ScmPullRequestField(StringEnum):
    TITLE = 'title'
    NUMBER = 'number'
    WEB_URL = 'webUrl'
    SOURCE_REPOSITORY_OWNER = 'sourceRepositoryOwner'
    SOURCE_REPOSITORY_NAME = 'sourceRepositoryName'
    SOURCE_BRANCH_NAME = 'sourceBranchName'
    DESTINATION_REPOSITORY_OWNER = 'destinationRepositoryOwner'
    DESTINATION_REPOSITORY_NAME = 'destinationRepositoryName'
    DESTINATION_BRANCH_NAME = 'destinationBranchName'
    IS_CLOSED = 'isClosed'
    IS_CROSS_REPOSITORY = 'isCrossRepository'
    REPOSITORY = 'repository'

class SubscriptionAppStoreReviewScreenshotField(StringEnum):
    FILE_SIZE = 'fileSize'
    FILE_NAME = 'fileName'
    SOURCE_FILE_CHECKSUM = 'sourceFileChecksum'
    IMAGE_ASSET = 'imageAsset'
    ASSET_TOKEN = 'assetToken'
    ASSET_TYPE = 'assetType'
    UPLOAD_OPERATIONS = 'uploadOperations'
    ASSET_DELIVERY_STATE = 'assetDeliveryState'
    SUBSCRIPTION = 'subscription'

class SubscriptionAvailabilityField(StringEnum):
    AVAILABLE_IN_NEW_TERRITORIES = 'availableInNewTerritories'
    AVAILABLE_TERRITORIES = 'availableTerritories'

class SubscriptionGroupLocalizationField(StringEnum):
    NAME = 'name'
    CUSTOM_APP_NAME = 'customAppName'
    LOCALE = 'locale'
    STATE = 'state'
    SUBSCRIPTION_GROUP = 'subscriptionGroup'

class SubscriptionField(StringEnum):
    NAME = 'name'
    PRODUCT_ID = 'productId'
    FAMILY_SHARABLE = 'familySharable'
    STATE = 'state'
    SUBSCRIPTION_PERIOD = 'subscriptionPeriod'
    REVIEW_NOTE = 'reviewNote'
    GROUP_LEVEL = 'groupLevel'
    SUBSCRIPTION_LOCALIZATIONS = 'subscriptionLocalizations'
    APP_STORE_REVIEW_SCREENSHOT = 'appStoreReviewScreenshot'
    GROUP = 'group'
    INTRODUCTORY_OFFERS = 'introductoryOffers'
    PROMOTIONAL_OFFERS = 'promotionalOffers'
    OFFER_CODES = 'offerCodes'
    PRICES = 'prices'
    PRICE_POINTS = 'pricePoints'
    PROMOTED_PURCHASE = 'promotedPurchase'
    SUBSCRIPTION_AVAILABILITY = 'subscriptionAvailability'
    WIN_BACK_OFFERS = 'winBackOffers'
    IMAGES = 'images'

class SubscriptionImageField(StringEnum):
    FILE_SIZE = 'fileSize'
    FILE_NAME = 'fileName'
    SOURCE_FILE_CHECKSUM = 'sourceFileChecksum'
    ASSET_TOKEN = 'assetToken'
    IMAGE_ASSET = 'imageAsset'
    UPLOAD_OPERATIONS = 'uploadOperations'
    STATE = 'state'
    SUBSCRIPTION = 'subscription'

class SubscriptionLocalizationField(StringEnum):
    NAME = 'name'
    LOCALE = 'locale'
    DESCRIPTION = 'description'
    STATE = 'state'
    SUBSCRIPTION = 'subscription'

class SubscriptionOfferCodeCustomCodeField(StringEnum):
    CUSTOM_CODE = 'customCode'
    NUMBER_OF_CODES = 'numberOfCodes'
    CREATED_DATE = 'createdDate'
    EXPIRATION_DATE = 'expirationDate'
    ACTIVE = 'active'
    OFFER_CODE = 'offerCode'

class SubscriptionOfferCodeOneTimeUseCodeField(StringEnum):
    NUMBER_OF_CODES = 'numberOfCodes'
    CREATED_DATE = 'createdDate'
    EXPIRATION_DATE = 'expirationDate'
    ACTIVE = 'active'
    OFFER_CODE = 'offerCode'
    VALUES = 'values'

class SubscriptionOfferCodeField(StringEnum):
    NAME = 'name'
    CUSTOMER_ELIGIBILITIES = 'customerEligibilities'
    OFFER_ELIGIBILITY = 'offerEligibility'
    DURATION = 'duration'
    OFFER_MODE = 'offerMode'
    NUMBER_OF_PERIODS = 'numberOfPeriods'
    TOTAL_NUMBER_OF_CODES = 'totalNumberOfCodes'
    ACTIVE = 'active'
    SUBSCRIPTION = 'subscription'
    ONE_TIME_USE_CODES = 'oneTimeUseCodes'
    CUSTOM_CODES = 'customCodes'
    PRICES = 'prices'

class SubscriptionOfferCodePriceField(StringEnum):
    TERRITORY = 'territory'
    SUBSCRIPTION_PRICE_POINT = 'subscriptionPricePoint'

class SubscriptionPricePointField(StringEnum):
    CUSTOMER_PRICE = 'customerPrice'
    PROCEEDS = 'proceeds'
    PROCEEDS_YEAR2 = 'proceedsYear2'
    TERRITORY = 'territory'
    EQUALIZATIONS = 'equalizations'

class SubscriptionPromotionalOfferField(StringEnum):
    DURATION = 'duration'
    NAME = 'name'
    NUMBER_OF_PERIODS = 'numberOfPeriods'
    OFFER_CODE = 'offerCode'
    OFFER_MODE = 'offerMode'
    SUBSCRIPTION = 'subscription'
    PRICES = 'prices'

class SubscriptionPromotionalOfferPriceField(StringEnum):
    TERRITORY = 'territory'
    SUBSCRIPTION_PRICE_POINT = 'subscriptionPricePoint'

class SubscriptionIntroductoryOfferField(StringEnum):
    START_DATE = 'startDate'
    END_DATE = 'endDate'
    DURATION = 'duration'
    OFFER_MODE = 'offerMode'
    NUMBER_OF_PERIODS = 'numberOfPeriods'
    SUBSCRIPTION = 'subscription'
    TERRITORY = 'territory'
    SUBSCRIPTION_PRICE_POINT = 'subscriptionPricePoint'

class SubscriptionPriceField(StringEnum):
    START_DATE = 'startDate'
    PRESERVED = 'preserved'
    TERRITORY = 'territory'
    SUBSCRIPTION_PRICE_POINT = 'subscriptionPricePoint'

class WinBackOfferField(StringEnum):
    REFERENCE_NAME = 'referenceName'
    OFFER_ID = 'offerId'
    DURATION = 'duration'
    OFFER_MODE = 'offerMode'
    PERIOD_COUNT = 'periodCount'
    CUSTOMER_ELIGIBILITY_PAID_SUBSCRIPTION_DURATION_IN_MONTHS = 'customerEligibilityPaidSubscriptionDurationInMonths'
    CUSTOMER_ELIGIBILITY_TIME_SINCE_LAST_SUBSCRIBED_IN_MONTHS = 'customerEligibilityTimeSinceLastSubscribedInMonths'
    CUSTOMER_ELIGIBILITY_WAIT_BETWEEN_OFFERS_IN_MONTHS = 'customerEligibilityWaitBetweenOffersInMonths'
    START_DATE = 'startDate'
    END_DATE = 'endDate'
    PRIORITY = 'priority'
    PROMOTION_INTENT = 'promotionIntent'
    PRICES = 'prices'

class UserInvitationField(StringEnum):
    EMAIL = 'email'
    FIRST_NAME = 'firstName'
    LAST_NAME = 'lastName'
    EXPIRATION_DATE = 'expirationDate'
    ROLES = 'roles'
    ALL_APPS_VISIBLE = 'allAppsVisible'
    PROVISIONING_ALLOWED = 'provisioningAllowed'
    VISIBLE_APPS = 'visibleApps'

class UserField(StringEnum):
    USERNAME = 'username'
    FIRST_NAME = 'firstName'
    LAST_NAME = 'lastName'
    ROLES = 'roles'
    ALL_APPS_VISIBLE = 'allAppsVisible'
    PROVISIONING_ALLOWED = 'provisioningAllowed'
    VISIBLE_APPS = 'visibleApps'

class WebhookField(StringEnum):
    ENABLED = 'enabled'
    EVENT_TYPES = 'eventTypes'
    NAME = 'name'
    URL = 'url'
    APP = 'app'
    DELIVERIES = 'deliveries'

class WinBackOfferPriceField(StringEnum):
    TERRITORY = 'territory'
    SUBSCRIPTION_PRICE_POINT = 'subscriptionPricePoint'

class AppClipAdvancedExperienceLocalizationField(StringEnum):
    LANGUAGE = 'language'
    TITLE = 'title'
    SUBTITLE = 'subtitle'

class AppKeywordField(StringEnum):

class TerritoryAgeRatingField(StringEnum):
    APP_STORE_AGE_RATING = 'appStoreAgeRating'
    TERRITORY = 'territory'

class AppTagField(StringEnum):
    NAME = 'name'
    VISIBLE_IN_APP_STORE = 'visibleInAppStore'
    TERRITORIES = 'territories'

class CustomerReviewSummarizationField(StringEnum):
    CREATED_DATE = 'createdDate'
    LOCALE = 'locale'
    PLATFORM = 'platform'
    TEXT = 'text'
    TERRITORY = 'territory'

class MarketplaceSearchDetailField(StringEnum):
    CATALOG_URL = 'catalogUrl'

class BetaRecruitmentCriterionCompatibleBuildCheckField(StringEnum):
    HAS_COMPATIBLE_BUILD = 'hasCompatibleBuild'

class BuildBundleField(StringEnum):
    BUNDLE_ID = 'bundleId'
    BUNDLE_TYPE = 'bundleType'
    SDK_BUILD = 'sdkBuild'
    PLATFORM_BUILD = 'platformBuild'
    FILE_NAME = 'fileName'
    HAS_SIRIKIT = 'hasSirikit'
    HAS_ON_DEMAND_RESOURCES = 'hasOnDemandResources'
    HAS_PRERENDERED_ICON = 'hasPrerenderedIcon'
    USES_LOCATION_SERVICES = 'usesLocationServices'
    IS_IOS_BUILD_MAC_APP_STORE_COMPATIBLE = 'isIosBuildMacAppStoreCompatible'
    INCLUDES_SYMBOLS = 'includesSymbols'
    D_SYM_URL = 'dSYMUrl'
    SUPPORTED_ARCHITECTURES = 'supportedArchitectures'
    REQUIRED_CAPABILITIES = 'requiredCapabilities'
    DEVICE_PROTOCOLS = 'deviceProtocols'
    LOCALES = 'locales'
    ENTITLEMENTS = 'entitlements'
    BA_DOWNLOAD_ALLOWANCE = 'baDownloadAllowance'
    BA_MAX_INSTALL_SIZE = 'baMaxInstallSize'
    APP_CLIP_DOMAIN_CACHE_STATUS = 'appClipDomainCacheStatus'
    APP_CLIP_DOMAIN_DEBUG_STATUS = 'appClipDomainDebugStatus'
    BETA_APP_CLIP_INVOCATIONS = 'betaAppClipInvocations'
    BUILD_BUNDLE_FILE_SIZES = 'buildBundleFileSizes'

class AppClipDomainStatuseField(StringEnum):
    DOMAINS = 'domains'
    LAST_UPDATED_DATE = 'lastUpdatedDate'

class BetaAppClipInvocationLocalizationField(StringEnum):
    TITLE = 'title'
    LOCALE = 'locale'

class BuildBundleFileSizeField(StringEnum):
    DEVICE_MODEL = 'deviceModel'
    OS_VERSION = 'osVersion'
    DOWNLOAD_BYTES = 'downloadBytes'
    INSTALL_BYTES = 'installBytes'

class DiagnosticSignatureField(StringEnum):
    DIAGNOSTIC_TYPE = 'diagnosticType'
    SIGNATURE = 'signature'
    WEIGHT = 'weight'
    INSIGHT = 'insight'
    LOGS = 'logs'

class WebhookDeliveryField(StringEnum):
    CREATED_DATE = 'createdDate'
    DELIVERY_STATE = 'deliveryState'
    ERROR_MESSAGE = 'errorMessage'
    REDELIVERY = 'redelivery'
    SENT_DATE = 'sentDate'
    REQUEST = 'request'
    RESPONSE = 'response'
    EVENT = 'event'

class WebhookEventField(StringEnum):
    EVENT_TYPE = 'eventType'
    PAYLOAD = 'payload'
    PING = 'ping'
    CREATED_DATE = 'createdDate'

